import { inputSchema } from "./index.ts";

export const form8994DirectEmployer = inputSchema.parse({
  source_type: "direct_schedule_c",
  schedule_c_business_reference: "boise-design-2025",
  proprietor_ssn: "123456789",
  employer_ein: "825555123",
  written_policy_reference: "2025-employee-family-leave-policy",
  policy_adopted_date: "2024-12-01",
  policy_effective_date: "2025-01-01",
  full_time_annual_leave_weeks: 2,
  full_time_usual_weekly_hours: 40,
  all_qualifying_employee_classes_covered_confirmed: true,
  policy_leave_specifically_designated_for_fmla_confirmed: true,
  noninterference_language_and_compliance_confirmed: true,
  no_pass_through_credit_confirmed: true,
  no_controlled_group_or_common_control_confirmed: true,
  schedule_c_wage_ledger_reference: "2025-boise-design-payroll",
  other_schedule_c_wages: 44_400,
  employees: [{
    employee_name: "A Example",
    employee_ssn: "123450001",
    payroll_ledger_reference: "2025-leave-pay-a",
    prior_2024_compensation_record_reference: "2024-compensation-a",
    prior_2024_compensation: 80_000,
    at_least_one_year_employed_on_leave_start_confirmed: true,
    qualifying_leave_purpose: "birth_or_child_care",
    leave_start_date: "2025-04-01",
    leave_end_date: "2025-04-14",
    normal_hourly_wage: 40,
    usual_weekly_hours: 40,
    policy_annual_leave_weeks_for_employee: 2,
    leave_hours: 80,
    leave_weeks: 2,
    policy_wage_replacement_rate: 0.75,
    employer_paid_qualifying_leave_wages: 2_400,
    no_state_or_local_required_or_paid_wages_included_confirmed: true,
    no_other_general_business_credit_wage_overlap_confirmed: true,
    no_other_leave_purpose_wages_included_confirmed: true,
  }, {
    employee_name: "B Example",
    employee_ssn: "123450002",
    payroll_ledger_reference: "2025-leave-pay-b",
    prior_2024_compensation_record_reference: "2024-compensation-b",
    prior_2024_compensation: 72_000,
    at_least_one_year_employed_on_leave_start_confirmed: true,
    qualifying_leave_purpose: "own_serious_health_condition",
    leave_start_date: "2025-06-01",
    leave_end_date: "2025-06-14",
    normal_hourly_wage: 40,
    usual_weekly_hours: 40,
    policy_annual_leave_weeks_for_employee: 2,
    leave_hours: 80,
    leave_weeks: 2,
    policy_wage_replacement_rate: 1,
    employer_paid_qualifying_leave_wages: 3_200,
    no_state_or_local_required_or_paid_wages_included_confirmed: true,
    no_other_general_business_credit_wage_overlap_confirmed: true,
    no_other_leave_purpose_wages_included_confirmed: true,
  }],
});

export const form8994MatchedPending = {
  f8994: form8994DirectEmployer,
  f3800: {
    f8994_direct_employer_credit: {
      credit_amount: 1_250,
      schedule_c_business_reference: "boise-design-2025",
      schedule_c_wage_ledger_reference: "2025-boise-design-payroll",
      subject_to_passive_activity_limit: false,
    },
    form8994_applied_credit: 1_250,
  },
  f1040: { taxpayer_ssn: "123-45-6789" },
  schedule_c: {
    schedule_cs: [{
      line_a_principal_business: "Design",
      line_b_business_code: "541400",
      line_c_business_name: "Boise Design",
      business_reference: "boise-design-2025",
      proprietor_recipient: "T",
      line_d_ein: "825555123",
      line_f_accounting_method: "cash",
      line_g_material_participation: true,
      line_1_gross_receipts: 100_000,
      line_26_wages: 50_000,
      line_26_other_employment_credits: 1_250,
    }],
  },
};
