import type { PdfReviewFixture } from "./review-fixtures.ts";
import { FilingStatus } from "../../nodes/types.ts";

/** Synthetic reviewed election with independently allocated filed half-SE tax. */
export function twoBusinessAggregationFixture(
  base: PdfReviewFixture,
  wageBase: PdfReviewFixture,
): PdfReviewFixture {
  const north = {
    line_a_principal_business: "Retail",
    line_b_business_code: "459999",
    line_c_business_name: "North Store",
    line_d_ein: "123456789",
    business_reference: "north-2025",
    proprietor_recipient: "T" as const,
    line_f_accounting_method: "cash" as const,
    line_g_material_participation: true,
    line_i_made_1099_payments: false,
    line_32_at_risk: "a" as const,
    line_1_gross_receipts: 120_000,
    line_26_wages: 20_000,
    qbi_specified_service: false,
    qbi_w2_wages: 20_000,
    qbi_unadjusted_basis: 100_000,
  };
  const south = {
    line_a_principal_business: "Retail",
    line_b_business_code: "459999",
    line_c_business_name: "South Store",
    line_d_ein: "987654321",
    business_reference: "south-2025",
    proprietor_recipient: "T" as const,
    line_f_accounting_method: "cash" as const,
    line_g_material_participation: true,
    line_i_made_1099_payments: false,
    line_32_at_risk: "a" as const,
    line_1_gross_receipts: 90_000,
    line_26_wages: 10_000,
    qbi_specified_service: false,
    qbi_w2_wages: 10_000,
    qbi_unadjusted_basis: 100_000,
  };
  const staged = {
    filing_status: FilingStatus.Single,
    taxable_income: 300_000,
    net_capital_gain: 0,
    qbi: 177_589,
    w2_wages: 30_000,
    unadjusted_basis: 200_000,
    qbi_no_prior_loss_or_suspended_loss_confirmed: true,
    aggregation_groups: [{
      group_name: "Retail Group",
      business_names: ["North Store", "South Store"],
      combined_for_limitation: true,
    }],
    aggregation_filing_details: {
      group_name: "Retail Group",
      group_description:
        "Two commonly owned retail stores sharing personnel and purchasing",
      common_owner_ssn: "111223333",
      tax_year_end: "2025-12-31",
      tax_year_end_source_reference: "calendar-year-ledger",
      election_history: {
        status: "new_2025",
        no_prior_election_confirmed: true,
      },
      rpe_aggregation_present: false,
      no_other_business_adjustments_confirmed: true,
      qualified_dividends_zero_confirmed: true,
      operational_factors: [{
        factor: "common_products",
        explanation: "Both stores sell the same merchandise",
        source_reference: "inventory-catalog",
      }, {
        factor: "shared_facilities_or_functions",
        explanation: "Both stores share purchasing and payroll staff",
        source_reference: "operations-ledger",
      }],
      members: [{
        business_reference: "north-2025",
        business_name: "North Store",
        ein: "123456789",
        qbi: 98_661,
        w2_wages: 20_000,
        ubia: 100_000,
        owner_share_pct: 100,
        ownership_start_date: "2020-01-01",
        owned_on_2025_12_31: true,
        ownership_source_reference: "north-ownership-ledger",
        qbi_adjustments: {
          deductible_se_tax: 1_339,
          self_employed_health_insurance: 0,
          qualified_retirement_plan: 0,
          no_other_attributable_adjustments_confirmed: true,
          allocation_method_description:
            "Deductible SE tax allocated by each store's net profit share",
          allocation_worksheet_reference: "se-allocation-2025",
          allocation_worksheet_reviewed_by: "Tax reviewer",
          allocation_worksheet_review_date: "2026-02-01",
        },
        source_schedule_c: north,
      }, {
        business_reference: "south-2025",
        business_name: "South Store",
        ein: "987654321",
        qbi: 78_928,
        w2_wages: 10_000,
        ubia: 100_000,
        owner_share_pct: 100,
        ownership_start_date: "2025-01-01",
        owned_on_2025_12_31: true,
        ownership_source_reference: "south-ownership-ledger",
        qbi_adjustments: {
          deductible_se_tax: 1_072,
          self_employed_health_insurance: 0,
          qualified_retirement_plan: 0,
          no_other_attributable_adjustments_confirmed: true,
          allocation_method_description:
            "Deductible SE tax allocated by each store's net profit share",
          allocation_worksheet_reference: "se-allocation-2025",
          allocation_worksheet_reviewed_by: "Tax reviewer",
          allocation_worksheet_review_date: "2026-02-01",
        },
        source_schedule_c: south,
      }],
    },
  };
  return {
    id: "single-form8995a-two-business-aggregation",
    filer: base.filer,
    inputs: {
      general: {
        ...(base.inputs.general as Record<string, unknown>),
        qbi_no_prior_loss_or_suspended_loss_confirmed: true,
        qbi_not_patron_of_specified_cooperative_confirmed: true,
      },
      w2: [{
        ...(wageBase.inputs.w2 as Record<string, unknown>[])[0],
        employee_ssn: "111-22-3333",
        box1_wages: 300_000,
        box3_ss_wages: 176_100,
        box4_ss_withheld: 10_918.20,
        box5_medicare_wages: 300_000,
        box6_medicare_withheld: 4_350,
        box2_fed_withheld: 90_000,
      }],
      schedule_c: [north, south],
      qbi_aggregation: {
        aggregation_groups: staged.aggregation_groups,
        qbi_no_prior_loss_or_suspended_loss_confirmed: true,
        aggregation_filing_details: staged.aggregation_filing_details,
      },
    },
    expectedPdfForms: [
      "f1040",
      "schedule1",
      "schedule2",
      "schedule_c",
      "schedule_c",
      "schedule_se",
      "form8959",
      "form8960",
      "form8995a",
      "form8995a_schedule_b",
    ],
    reviewFocus: [
      "Two retained Schedule C sources produce profits100000 and80000 and filed half-SE deduction2411 allocated1339/1072",
      "Schedule B member identities and QBI98661/78928 reconcile to aggregated parent QBI177589/wages30000/UBIA200000",
      "Parent aggregated checkbox and wage-limited15000 deduction reach finalized Form1040 and both required native documents",
    ],
  };
}
