import { ForeignAssetType } from "../../../nodes/inputs/f8938/index.ts";

/** Reviewed-shape fixture only; no real taxpayer or institution identifiers. */
export function form8938Fixture() {
  return {
    specified_individual_type: "us_citizen",
    annual_income_tax_return_required: true,
    filing_status: "single",
    residence: { location: "united_states" },
    max_value_all_assets: 100_000,
    year_end_value_all_assets: 95_000,
    assets: [
      {
        asset_id: "account-1",
        asset_type: ForeignAssetType.DepositAccount,
        description: "CHF deposit account",
        asset_identifier: "CH-1001",
        country: "CH",
        institution_or_issuer_name: "Example Swiss Bank",
        institution_or_issuer_address: {
          line1: "10 Bankstrasse",
          city: "Zurich",
          country: "CH",
          postal_code: "8001",
        },
        owner: "taxpayer",
        currency_code: "CHF",
        year_end_exchange_rate_usd_per_unit: 1.25,
        exchange_rate_source: "U.S. Treasury Fiscal Service",
        exchange_rate_date: "2025-12-31",
        maximum_value_native: 64_000,
        year_end_value_native: 44_000,
        maximum_value_usd: 80_000,
        year_end_value_usd: 55_000,
        tax_items: [{
          kind: "interest",
          amount_usd: 200,
          filed_form_and_line: "Schedule B line 1",
        }],
      },
      {
        asset_id: "stock-1",
        asset_type: ForeignAssetType.ForeignStock,
        foreign_entity_type: "corporation",
        description: "100 shares of Example Foreign Corp.",
        asset_identifier: "STOCK-100",
        country: "DE",
        institution_or_issuer_name: "Example Foreign Corp.",
        institution_or_issuer_address: {
          line1: "20 Market St",
          city: "Berlin",
          country: "DE",
          postal_code: "10115",
        },
        owner: "taxpayer",
        currency_code: "USD",
        year_end_exchange_rate_usd_per_unit: 1,
        exchange_rate_source: "USD denominated",
        exchange_rate_date: "2025-12-31",
        maximum_value_native: 40_000,
        year_end_value_native: 30_000,
        maximum_value_usd: 40_000,
        year_end_value_usd: 30_000,
        tax_items: [{
          kind: "dividends",
          amount_usd: 100,
          filed_form_and_line: "Form 1040 line 3b",
        }],
      },
      {
        asset_id: "excepted-pfic-1",
        asset_type: ForeignAssetType.ForeignStock,
        foreign_entity_type: "corporation",
        description: "PFIC shares reported on Form 8621",
        asset_identifier: "PFIC-1",
        country: "FR",
        institution_or_issuer_name: "Example PFIC",
        institution_or_issuer_address: {
          line1: "30 Rue A",
          city: "Paris",
          country: "FR",
          postal_code: "75001",
        },
        owner: "taxpayer",
        currency_code: "USD",
        year_end_exchange_rate_usd_per_unit: 1,
        exchange_rate_source: "USD denominated",
        exchange_rate_date: "2025-12-31",
        maximum_value_native: 10_000,
        year_end_value_native: 10_000,
        maximum_value_usd: 10_000,
        year_end_value_usd: 10_000,
        excepted_on_form: "8621",
        filed_exception_form_reference: "Form 8621 PFIC-1 TY2025",
        tax_items: [],
      },
    ],
  };
}
