import type { F453AInterestInput } from "./index.ts";

export const twoObligation453aFixture: F453AInterestInput = {
  seller_taxpayer_ssn: "111223333",
  tax_year_end: "2025-12-31",
  underpayment_rate: 0.07,
  underpayment_rate_source_reference: "https://www.irs.gov/irb/2025-37_IRB",
  origin_year_workpapers: [{
    origin_year: 2025,
    aggregate_qualifying_face_amount: 6_000_000,
    applicable_percentage: 1 / 6,
    origin_year_inventory_reference: "2025 origin-year obligation inventory",
  }],
  obligations: [{
    obligation_id: "2025-note-a",
    transaction_id: "2025-sale-a",
    origin_year: 2025,
    transaction_sale_price: 4_500_000,
    property_kind: "nonfarm_real_property",
    seller_is_dealer: false,
    origin_year_end_face_amount: 4_000_000,
    year_end_unpaid_face_amount: 4_000_000,
    gross_profit_percentage: 0.75,
    year_end_unrecognized_gain: 3_000_000,
    gain_character: "long_term_capital_gain",
    sale_source_reference: "2025 signed sale A",
    obligation_source_reference: "2025 signed note A",
    year_end_balance_source_reference: "2025 note A ledger",
  }, {
    obligation_id: "2025-note-b",
    transaction_id: "2025-sale-b",
    origin_year: 2025,
    transaction_sale_price: 2_500_000,
    property_kind: "nonfarm_business_or_investment_personal_property",
    seller_is_dealer: false,
    origin_year_end_face_amount: 2_000_000,
    year_end_unpaid_face_amount: 2_000_000,
    gross_profit_percentage: 0.5,
    year_end_unrecognized_gain: 1_000_000,
    gain_character: "ordinary",
    sale_source_reference: "2025 signed sale B",
    obligation_source_reference: "2025 signed note B",
    year_end_balance_source_reference: "2025 note B ledger",
  }],
};
