import { z } from "zod";

// Pub. 555 mandatory community-property states are deliberately absent. AK/TN/SD
// need the explicit election/property review below; a state code alone proves nothing.
const ordinaryDomicileState = z.enum([
  "AK",
  "AL",
  "AR",
  "CO",
  "CT",
  "DC",
  "DE",
  "FL",
  "GA",
  "HI",
  "IA",
  "IL",
  "IN",
  "KS",
  "KY",
  "MA",
  "MD",
  "ME",
  "MI",
  "MN",
  "MO",
  "MS",
  "MT",
  "NC",
  "ND",
  "NE",
  "NH",
  "NJ",
  "NY",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "UT",
  "VA",
  "VT",
  "WV",
  "WY",
]);

/** Source records establish domicile/property character independently of mail. */
export const mfsSstbFilingReviewSchema = z.object({
  domicile_state: ordinaryDomicileState,
  spouse_domicile_state: ordinaryDomicileState,
  full_year_noncommunity_domiciles_confirmed: z.literal(true),
  domicile_record_reference: z.string().trim().min(1),
  spouse_domicile_record_reference: z.string().trim().min(1),
  property_regime_record_reference: z.string().trim().min(1),
  no_elected_community_property_regime_confirmed: z.literal(true),
  no_current_or_retained_community_income_confirmed: z.literal(true),
  primary_separate_earnings_record_reference: z.string().trim().min(1),
  business_and_wages_are_primary_separate_income_confirmed: z.literal(true),
  mailing_address_state: z.string().regex(/^[A-Z]{2}$/),
  spouse_ssn: z.string().regex(/^\d{9}$/),
  spouse_deduction_record_reference: z.string().trim().min(1),
  spouse_does_not_itemize_confirmed: z.literal(true),
}).strict();
