import { z } from "zod";
import {
  dependentFilingSchema,
  inputSchema as generalInputSchema,
} from "../nodes/inputs/general/index.ts";

/** Fields emitted by the shared general node for the Form 1040 filer header. */
export const identityInputSchema = generalInputSchema.pick({
  filing_status: true,
  spouse_has_business_credit: true,
  taxpayer_first_name: true,
  taxpayer_middle_initial: true,
  taxpayer_last_name: true,
  taxpayer_ssn: true,
  taxpayer_ssn_valid_for_employment: true,
  taxpayer_ssn_issued_before_due_date: true,
  taxpayer_tin_issued_by_due_date: true,
  taxpayer_citizen_national_or_work_authorized: true,
  taxpayer_dob: true,
  taxpayer_blind: true,
  taxpayer_age_65_or_older: true,
  taxpayer_occupation: true,
  taxpayer_deceased: true,
  taxpayer_death_date: true,
  taxpayer_ip_pin: true,
  spouse_first_name: true,
  spouse_last_name: true,
  spouse_ssn: true,
  spouse_ssn_valid_for_employment: true,
  spouse_ssn_issued_before_due_date: true,
  spouse_tin_issued_by_due_date: true,
  spouse_citizen_national_or_work_authorized: true,
  spouse_dob: true,
  spouse_blind: true,
  spouse_age_65_or_older: true,
  spouse_occupation: true,
  spouse_deceased: true,
  spouse_death_date: true,
  spouse_ip_pin: true,
  address_line1: true,
  address_line2: true,
  address_city: true,
  address_state: true,
  address_zip: true,
  address_foreign_country: true,
  address_foreign_province_state: true,
  address_foreign_postal_code: true,
  digital_assets: true,
  presidential_campaign_fund_taxpayer: true,
  presidential_campaign_fund_spouse: true,
  extension_filed: true,
  mfs_spouse_itemizing: true,
  taxpayer_can_be_claimed_as_dependent: true,
  hoh_paid_more_than_half_home_costs: true,
  qss_spouse_death_year: true,
  taxpayer_signature_pin: true,
  spouse_signature_pin: true,
  bank_routing_number: true,
  bank_account_number: true,
  bank_account_type: true,
}).extend({
  dependent_count: z.number().int().nonnegative().default(0),
  qualifying_child_tax_credit_count: z.number().int().nonnegative().default(0),
  other_dependent_count: z.number().int().nonnegative().default(0),
  dependent_details: z.array(dependentFilingSchema).optional(),
});
