// Distribution codes retained by the TY2025 Form 1099-R source.
export enum DistributionCode {
  Code1 = "1",
  Code2 = "2",
  Code3 = "3",
  Code4 = "4",
  Code5 = "5",
  Code6 = "6",
  Code7 = "7",
  Code8 = "8",
  CodeA = "A",
  CodeB = "B",
  CodeC = "C",
  CodeD = "D",
  CodeE = "E",
  CodeF = "F",
  CodeG = "G",
  CodeH = "H",
  CodeJ = "J",
  CodeK = "K",
  CodeL = "L",
  CodeM = "M",
  CodeN = "N",
  CodeP = "P",
  CodeQ = "Q",
  CodeR = "R",
  CodeS = "S",
  CodeT = "T",
  CodeU = "U",
  CodeV = "V",
  CodeW = "W",
  CodeY = "Y",
}
