// TY2025 MeF Common/efileTypes.xsd CountryType annotations.
// Source SHA-256: d149341c9554ca338f18c68a9d34c55e3a8c41f0e2485058c54a11aae8bdf5e5.
// IRS country codes differ from ISO 3166 (for example, GM is Germany).
// Use this label for the Form 1040 paper foreign-address country field.
export const TY2025_IRS_COUNTRY_NAMES: Readonly<Record<string, string>> = {
  "AF": "Afghanistan",
  "AX": "Akrotiri",
  "AL": "Albania",
  "AG": "Algeria",
  "AQ": "American Samoa",
  "AN": "Andorra",
  "AO": "Angola",
  "AV": "Anguilla",
  "AY": "Antarctica",
  "AC": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AA": "Aruba",
  "AT": "Ashmore and Cartier Islands",
  "AS": "Australia",
  "AU": "Austria",
  "AJ": "Azerbaijan",
  "BF": "Bahamas",
  "BA": "Bahrain",
  "FQ": "Baker Island",
  "BG": "Bangladesh",
  "BB": "Barbados",
  "BO": "Belarus",
  "BE": "Belgium",
  "BH": "Belize",
  "BN": "Benin",
  "BD": "Bermuda",
  "BT": "Bhutan",
  "BL": "Bolivia",
  "BK": "Bosnia-Herzegovina",
  "BC": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "VI": "British Virgin Islands",
  "BX": "Brunei",
  "BU": "Bulgaria",
  "UV": "Burkina Faso",
  "BM": "Burma",
  "BY": "Burundi",
  "CB": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "CJ": "Cayman Islands",
  "CT": "Central African Republic",
  "CD": "Chad",
  "CI": "Chile",
  "CH": "China",
  "KT": "Christmas Island",
  "IP": "Clipperton Island",
  "CK": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "CN": "Comoros",
  "CF": "Congo (Brazzaville)",
  "CG": "Congo (Kinshasa)",
  "CW": "Cook Islands",
  "CR": "Coral Sea Islands",
  "CS": "Costa Rica",
  "IV": "Cote D'Ivoire (Ivory Coast)",
  "HR": "Croatia",
  "CU": "Cuba",
  "UC": "Curacao",
  "CY": "Cyprus",
  "EZ": "Czech Republic",
  "DA": "Denmark",
  "DX": "Dhekelia",
  "DJ": "Djibouti",
  "DO": "Dominica",
  "DR": "Dominican Republic",
  "TT": "East Timor",
  "EC": "Ecuador",
  "EG": "Egypt",
  "ES": "El Salvador",
  "EK": "Equatorial Guinea",
  "ER": "Eritrea",
  "EN": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (Islas Malvinas)",
  "FO": "Faroe Islands",
  "FM": "Federated States of Micronesia",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "FP": "French Polynesia",
  "FS": "French Southern and Antarctic Lands",
  "GB": "Gabon",
  "GA": "The Gambia",
  "GG": "Georgia",
  "GM": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GJ": "Grenada",
  "GQ": "Guam",
  "GT": "Guatemala",
  "GK": "Guernsey",
  "GV": "Guinea",
  "PU": "Guinea-Bissau",
  "GY": "Guyana",
  "HA": "Haiti",
  "HM": "Heard Island and McDonald Islands",
  "VT": "Holy See",
  "HO": "Honduras",
  "HK": "Hong Kong",
  "HQ": "Howland Island",
  "HU": "Hungary",
  "IC": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IZ": "Iraq",
  "EI": "Ireland",
  "IS": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JN": "Jan Mayen",
  "JA": "Japan",
  "DQ": "Jarvis Island",
  "JE": "Jersey",
  "JQ": "Johnston Atoll",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KQ": "Kingman Reef",
  "KR": "Kiribati",
  "KN": "Korea, Democratic People's Republic of (North)",
  "KS": "Korea, Republic of (South)",
  "KV": "Kosovo",
  "KU": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Laos",
  "LG": "Latvia",
  "LE": "Lebanon",
  "LT": "Lesotho",
  "LI": "Liberia",
  "LY": "Libya",
  "LS": "Liechtenstein",
  "LH": "Lithuania",
  "LU": "Luxembourg",
  "MC": "Macau",
  "MK": "Macedonia",
  "MA": "Madagascar",
  "MI": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "IM": "Man, Isle of",
  "RM": "Marshall Islands",
  "MR": "Mauritania",
  "MP": "Mauritius",
  "MX": "Mexico",
  "MQ": "Midway Islands",
  "MD": "Moldova",
  "MN": "Monaco",
  "MG": "Mongolia",
  "MJ": "Montenegro",
  "MH": "Montserrat",
  "MO": "Morocco",
  "MZ": "Mozambique",
  "WA": "Namibia",
  "NR": "Nauru",
  "BQ": "Navassa Island",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NU": "Nicaragua",
  "NG": "Niger",
  "NI": "Nigeria",
  "NE": "Niue",
  "NF": "Norfolk Island",
  "CQ": "Northern Mariana Islands",
  "NO": "Norway",
  "MU": "Oman",
  "OC": "Other Country",
  "PK": "Pakistan",
  "PS": "Palau",
  "LQ": "Palmyra Atoll",
  "PM": "Panama",
  "PP": "Papua-New Guinea",
  "PF": "Paracel Islands",
  "PA": "Paraguay",
  "PE": "Peru",
  "RP": "Philippines",
  "PC": "Pitcairn Islands",
  "PL": "Poland",
  "PO": "Portugal",
  "RQ": "Puerto Rico",
  "QA": "Qatar",
  "RO": "Romania",
  "RS": "Russia",
  "RW": "Rwanda",
  "TB": "Saint Barthelemy",
  "RN": "Saint Martin",
  "WS": "Samoa",
  "SM": "San Marino",
  "TP": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "SG": "Senegal",
  "RI": "Serbia",
  "SE": "Seychelles",
  "SL": "Sierra Leone",
  "SN": "Singapore",
  "NN": "Sint Maarten",
  "LO": "Slovakia",
  "SI": "Slovenia",
  "BP": "Solomon Islands",
  "SO": "Somalia",
  "SF": "South Africa",
  "SX": "South Georgia and the South Sandwich Islands",
  "OD": "South Sudan",
  "SP": "Spain",
  "PG": "Spratly Islands",
  "CE": "Sri Lanka",
  "SH": "St. Helena",
  "SC": "St. Kitts and Nevis",
  "ST": "St. Lucia Island",
  "SB": "St. Pierre and Miquelon",
  "VC": "St. Vincent and the Grenadines",
  "SU": "Sudan",
  "NS": "Suriname",
  "SV": "Svalbard",
  "WZ": "Swaziland",
  "SW": "Sweden",
  "SZ": "Switzerland",
  "SY": "Syria",
  "TW": "Taiwan",
  "TI": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TO": "Togo",
  "TL": "Tokelau",
  "TN": "Tonga",
  "TD": "Trinidad and Tobago",
  "TS": "Tunisia",
  "TU": "Turkey",
  "TX": "Turkmenistan",
  "TK": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UP": "Ukraine",
  "AE": "United Arab Emirates",
  "UK": "United Kingdom (England, Northern Ireland, Scotland, and Wales)",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "NH": "Vanuatu",
  "VE": "Venezuela",
  "VM": "Vietnam",
  "VQ": "Virgin Islands",
  "WQ": "Wake Island",
  "WF": "Wallis and Futuna",
  "WI": "Western Sahara",
  "YM": "Yemen (Aden)",
  "ZA": "Zambia",
  "ZI": "Zimbabwe",
};

export function ty2025IrsCountryName(code: string): string {
  if (!Object.hasOwn(TY2025_IRS_COUNTRY_NAMES, code)) {
    throw new Error(
      `Form 1040 PDF foreign address needs a TY2025 IRS country code; received ${code}`,
    );
  }
  return TY2025_IRS_COUNTRY_NAMES[code];
}
