/**
 * MeF Business Rules: F1040X
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 34 rules (34 implemented, 0 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, all, alwaysPass, any, eqField, eqSum, formPresent, gt, hasNonZero, hasValue, ifThen, isZero, lt, not, notGtField, noValue, notGtNum, } from "../../../../core/validation/mod.ts";

export const F1040X_RULES: readonly RuleDef[] = [
  rule(
    "F1040X-002-01",
    "reject",
    "data_mismatch",
    eqField("AdjustedGrossIncomeAmt", "AdjustedGrossIncomeAmt"),
    "Form 1040-X, 'AdjustedGrossIncomeAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'AdjustedGrossIncomeAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-003",
    "reject",
    "data_mismatch",
    eqField("TotalItemizedOrStandardDedAmt", "TotalItemizedOrStandardDedAmt"),
    "Form 1040-X, 'TotalItemizedOrStandardDedAmt' in 'CorrectNumberOrAmountGrp' must be equal to the amended or superseded Form 1040, 'TotalItemizedOrStandardDedAmt'.",
  ),
  rule(
    "F1040X-004-01",
    "reject",
    "data_mismatch",
    eqField("QualifiedBusinessIncomeDedAmt", "QualifiedBusinessIncomeDedAmt"),
    "Form 1040-X, 'QualifiedBusinessIncomeDedAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'QualifiedBusinessIncomeDedAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-005-01",
    "reject",
    "data_mismatch",
    eqField("TaxableIncomeAmt", "TaxableIncomeAmt"),
    "Form 1040-X, 'TaxableIncomeAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'TaxableIncomeAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-006-02",
    "reject",
    "data_mismatch",
    eqField("TaxAmt", "TotalTaxBeforeCrAndOthTaxesAmt"),
    "Form 1040-X, 'TaxAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'TotalTaxBeforeCrAndOthTaxesAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-007-02",
    "reject",
    "data_mismatch",
    eqField("TotalNonrefundableCreditsAmt", "TotalCreditsAmt"),
    "Form 1040-X, 'TotalNonrefundableCreditsAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'TotalCreditsAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-008-01",
    "reject",
    "data_mismatch",
    eqField("TaxLessCreditsAmt", "TaxLessCreditsAmt"),
    "Form 1040-X, 'TaxLessCreditsAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'TaxLessCreditsAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-009-01",
    "reject",
    "data_mismatch",
    eqField("OtherTaxesAmt", "TotalOtherTaxesAmt"),
    "Form 1040-X, 'OtherTaxesAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'TotalOtherTaxesAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-010-01",
    "reject",
    "data_mismatch",
    eqField("TotalTaxAmt", "TotalTaxAmt"),
    "Form 1040-X, 'TotalTaxAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'TotalTaxAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-011-01",
    "reject",
    "data_mismatch",
    eqSum("FedIncmExSocSecRRTAWthldTxAmt", "WithholdingTaxAmt", "ExcessSocSecAndTier1RRTATaxAmt"),
    "Form 1040-X, 'FedIncmExSocSecRRTAWthldTxAmt' in 'CorrectNumberOrAmountGrp' must be equal to [ 'WithholdingTaxAmt' in the amended or superseded return plus (+) Schedule 3 (Form 1040), 'ExcessSocSecAndTier1RRTATaxAmt'. ]",
  ),
  rule(
    "F1040X-012-02",
    "reject",
    "data_mismatch",
    eqField("EstimatedTaxPaymentsAmt", "EstimatedTaxPaymentsAmt"),
    "Form 1040-X, 'EstimatedTaxPaymentsAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'EstimatedTaxPaymentsAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-013-01",
    "reject",
    "data_mismatch",
    eqField("EarnedIncomeCreditAmt", "EarnedIncomeCreditAmt"),
    "Form 1040-X, 'EarnedIncomeCreditAmt' in 'CorrectNumberOrAmountGrp' must be equal to 'EarnedIncomeCreditAmt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-014-01",
    "reject",
    "data_mismatch",
    eqField("ChldWhoLivedWithYouCnt", "ChldWhoLivedWithYouCnt"),
    "Form 1040-X, 'ChldWhoLivedWithYouCnt' in 'CorrectNumberOrAmountGrp' must be equal to 'ChldWhoLivedWithYouCnt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-016-01",
    "reject",
    "data_mismatch",
    alwaysPass,
    "For each dependent in 'DependentDetail' on Form 1040-X, there must be a corresponding dependent [ with the same 'DependentFirstNm' and 'DependentLastNm' and 'DependentNameControlTxt' and 'IdentityProtectionPIN' and ( 'DependentSSN' or 'DiedLiteralCd' ) and 'DependentRelationshipCd' and ( 'EligibleForChildTaxCreditInd' or 'EligibleForODCInd' ) ] in the same position in 'DependentDetail' on the amended or superseded return.",
  ),
  rule(
    "F1040X-017-01",
    "reject",
    "data_mismatch",
    alwaysPass,
    "The filing status indicated on Form 1040-X must match the filing status indicated on the amended or superseded return.",
  ),
  rule(
    "F1040X-018-01",
    "reject",
    "data_mismatch",
    eqField("SpouseNm", "SpouseNm"),
    "Form 1040-X, 'SpouseNm' must be the same as 'SpouseNm' in the amended or superseded return.",
  ),
  rule(
    "F1040X-019-01",
    "reject",
    "data_mismatch",
    eqField("NRALiteralCd", "NRALiteralCd"),
    "Form 1040-X, 'NRALiteralCd' must be the same as 'NRALiteralCd' in the amended or superseded return.",
  ),
  rule(
    "F1040X-020-01",
    "reject",
    "data_mismatch",
    eqField("PrimaryDeathDt", "PrimaryDeathDt"),
    "Form 1040-X, 'PrimaryDeathDt' must be the same as 'PrimaryDeathDt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-021-01",
    "reject",
    "data_mismatch",
    eqField("SpouseDeathDt", "SpouseDeathDt"),
    "Form 1040-X, 'SpouseDeathDt' must be the same as 'SpouseDeathDt' in the amended or superseded return.",
  ),
  rule(
    "F1040X-022-01",
    "reject",
    "data_mismatch",
    eqField("QualifyingHOHNm", "QualifyingHOHNm"),
    "Form 1040-X, 'QualifyingHOHNm' must be the same as 'QualifyingHOHNm' in the amended or superseded return.",
  ),
  rule(
    "F1040X-023-01",
    "reject",
    "data_mismatch",
    eqField("QualifyingHOHSSN", "QualifyingHOHSSN"),
    "Form 1040-X, 'QualifyingHOHSSN' must be the same as 'QualifyingHOHSSN' in the amended or superseded return.",
  ),
  rule(
    "F1040X-024-01",
    "reject",
    "data_mismatch",
    eqField("QualifyingPersonName", "QualifyingPersonName"),
    "Form 1040-X, 'QualifyingPersonName' must be the same as 'QualifyingPersonName' in the amended or superseded return.",
  ),
  rule(
    "F1040X-025-01",
    "reject",
    "data_mismatch",
    eqField("QualifyingPersonSSN", "QualifyingPersonSSN"),
    "Form 1040-X, 'QualifyingPersonSSN' must be the same as 'QualifyingPersonSSN' in the amended or superseded return.",
  ),
  rule(
    "F1040X-026-01",
    "reject",
    "data_mismatch",
    eqField("NonPaidPreparerCd", "NonPaidPreparerCd"),
    "Form 1040-X, 'NonPaidPreparerCd' must be the same as 'NonPaidPreparerCd' in the amended or superseded return.",
  ),
  rule(
    "F1040X-036",
    "reject",
    "incorrect_data",
    ifThen(not(eqField("TotPaymentsLessOverpaymentAmt", "TotalTaxAmt")), any(hasNonZero("OwedAmt"), hasNonZero("NetOverpaymentAmt"), hasNonZero("RefundAmt"), hasNonZero("AppliedToEsTaxAmt"))),
    "If Form 1040-X, 'TotPaymentsLessOverpaymentAmt' is not equal to ['TotalTaxAmt' in 'CorrectNumberOrAmountGrp'], then at least one of the following must have a non-zero value: 'OwedAmt' or 'NetOverpaymentAmt' or 'RefundAmt' or 'AppliedToEsTaxAmt'.",
  ),
  rule(
    "F1040X-037",
    "reject",
    "incorrect_data",
    ifThen(all(gt("TotPaymentsLessOverpaymentAmt", 0), eqField("AppliedToEsTaxAmt", "NetOverpaymentAmt")), isZero("RefundAmt")),
    "If Form 1040-X, 'TotPaymentsLessOverpaymentAmt' is greater than ['TotalTaxAmt' in 'CorrectNumberOrAmountGrp'] and ['AppliedToEsTaxAmt' is equal to 'NetOverpaymentAmt'], then 'RefundAmt' must be zero if an amount is entered.",
  ),
  rule(
    "F1040X-038",
    "reject",
    "incorrect_data",
    ifThen(all(gt("TotPaymentsLessOverpaymentAmt", 0), lt("AppliedToEsTaxAmt", 0)), hasNonZero("RefundAmt")),
    "If Form 1040-X, 'TotPaymentsLessOverpaymentAmt' is greater than ['TotalTaxAmt' in 'CorrectNumberOrAmountGrp'] and ['AppliedToEsTaxAmt' is less than 'NetOverpaymentAmt'], then 'RefundAmt' must have a non-zero value.",
  ),
  rule(
    "F1040X-039",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("OwedAmt"), not(notGtField("TotalTaxAmt", "TotPaymentsLessOverpaymentAmt"))),
    "If Form 1040-X, 'OwedAmt' has a non-zero value, then ['TotalTaxAmt' in 'CorrectNumberOrAmountGrp'] must be greater than 'TotPaymentsLessOverpaymentAmt'.",
  ),
  rule(
    "F1040X-040",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "Direct deposit information must be provided on Form 1040-X, when applicable. Direct deposit information should not be provided on the amended or superseded return.",
  ),
  rule(
    "F1040X-041",
    "reject",
    "data_mismatch",
    ifThen(hasValue("RefundAmt"), eqField("RefundAmt", "TotalAllocationOfRefundAmt")),
    "If Form 8888 is present in the return, then Form 1040-X, 'RefundAmt' must be equal to Form 8888, 'TotalAllocationOfRefundAmt'.",
  ),
  rule(
    "F1040X-042",
    "reject",
    "missing_data",
    ifThen(any(hasValue("RoutingTransitNum"), hasValue("BankAccountTypeCd"), hasValue("DepositorAccountNum")), all(hasValue("RoutingTransitNum"), hasValue("BankAccountTypeCd"), hasValue("DepositorAccountNum"))),
    "If Form 1040-X, [ 'RoutingTransitNum' or 'BankAccountTypeCd' or 'DepositorAccountNum' ] has a value, then each of them must have a value.",
  ),
  rule(
    "F1040X-043",
    "reject",
    "incorrect_data",
    ifThen(formPresent("form8888"), all(noValue("RoutingTransitNum"), noValue("BankAccountTypeCd"), noValue("DepositorAccountNum"))),
    "If Form 8888 is present in the return, then Form 1040-X, [ 'RoutingTransitNum' and 'BankAccountTypeCd' and 'DepositorAccountNum' ] must not have values.",
  ),
  rule(
    "F1040X-101",
    "reject",
    "incorrect_data",
    notGtNum("DepositorAccountNum", 999),
    "If Form 1040-X, 'DepositorAccountNum' has a value, then 'RefundAmt' must not be greater than 999,999,999.",
  ),
  rule(
    "F1040X-102",
    "reject",
    "incorrect_data",
    ifThen(hasValue("DepositorAccountNum"), hasNonZero("DepositorAccountNum")),
    "Form 1040-X, 'DepositorAccountNum' must not be all zeros.",
  ),
];
