/**
 * MeF Business Rules: F4136
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 89 rules (89 implemented, 0 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, alwaysPass, hasNonZero, hasValue, ifThen, any, isZero, } from "../../../../core/validation/mod.ts";

export const F4136_RULES: readonly RuleDef[] = [
  rule(
    "F4136-001-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxUseUndyedKrsnTxd044CrAmt"), hasNonZero("NontxUseUndyedKrsnTxd044_GallonsQty")),
    "If Form 4136, Line 4e(d) 'NontxUseUndyedKrsnTxd044CrAmt' has a non-zero value, then Line 4e(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-002-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxUseUndyedKrsnTxd219CrAmt"), hasNonZero("NontxUseUndyedKrsnTxd219_GallonsQty")),
    "If Form 4136, Line 4f(d) 'NontxUseUndyedKrsnTxd219CrAmt' has a non-zero value, then Line 4f(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-003-02",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontaxableUseOfGasolineCrAmt"), any(hasNonZero("OffHwyBusUseGasolineGalsQty"), hasNonZero("FarmingPurposesGasolineGalsQty"), hasNonZero("NontaxableUseOfGasoline_GallonsQty"))),
    "If Form 4136, Line 1c(d) 'NontaxableUseOfGasolineCrAmt' has a non-zero value, then Line 1a(c) 'OffHwyBusUseGasolineGalsQty' or Line 1b(c) 'FarmingPurposesGasolineGalsQty' or Line 1c(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-004-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("AviationGasolineCreditAmt"), hasNonZero("AviationGasolineGallonsQty")),
    "If Form 4136, Line 2a(d) 'AviationGasolineCreditAmt' has a non-zero value, Line 2a(c) 'AviationGasolineGallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-005-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("AviationNontxGasCrAmt"), hasNonZero("AviationNontxGas_GallonsQty")),
    "If Form 4136, Line 2b(d) 'AviationNontxGasCrAmt' has a non-zero value, then Form 4136 Line 2b(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-007-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("TrainUseOfUndyedDieselCrAmt"), hasNonZero("TrainUseOfUndyedDieselGalsQty")),
    "If Form 4136, Line 3c(d) 'TrainUseOfUndyedDieselCrAmt' has a non-zero value, then Line 3c(c) 'TrainUseOfUndyedDieselGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-008-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("BusUseOfUndyedDieselCreditAmt"), hasNonZero("BusUseOfUndyedDieselGalsQty")),
    "If Form 4136, Line 3d(d) 'BusUseOfUndyedDieselCreditAmt' has a non-zero value, then Line 3d(c) 'BusUseOfUndyedDieselGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-009-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("ExpUndyedDieselFuelCreditAmt"), hasNonZero("ExpUndyedDieselFuelGalsQty")),
    "If Form 4136, Line 3e(d) 'ExpUndyedDieselFuelCreditAmt' has a non-zero value, then Line 3e(c) 'ExpUndyedDieselFuelGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-011-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("BusUseOfUndyedKeroseneCrAmt"), hasNonZero("BusUseOfUndyedKeroseneGalsQty")),
    "If Form 4136, Line 4c(d) 'BusUseOfUndyedKeroseneCrAmt' has a non-zero value, then Line 4c(c) 'BusUseOfUndyedKeroseneGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-012-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("ExportedUndyedKeroseneCrAmt"), hasNonZero("ExportedUndyedKeroseneGalsQty")),
    "If Form 4136, Line 4d(d) 'ExportedUndyedKeroseneCrAmt' has a non-zero value, then Line 4d(c) 'ExportedUndyedKeroseneGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-013-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("KeroseneUsedInAvnTxd219CrAmt"), hasNonZero("KeroseneUsedInAvnTxd219GalsQty")),
    "If Form 4136, Line 5b(d) 'KeroseneUsedInAvnTxd219CrAmt' has a non-zero value, then Line 5b(c) 'KeroseneUsedInAvnTxd219GalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-014-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsUndyedDslUseStLclGovtCrAmt"), hasNonZero("SlsUndyedDslStLclGovtGalsQty")),
    "If Form 4136, Line 6a(d) 'SlsUndyedDslUseStLclGovtCrAmt' has a non-zero value, then Line 6a(c) 'SlsUndyedDslStLclGovtGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-016-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsUndyedKrsnUseBusCrAmt"), hasNonZero("SlsUndyedKrsnUseBusGalsQty")),
    "If Form 4136, Line 7c(d) 'SlsUndyedKrsnUseBusCrAmt' has a non-zero value then, Line 7c(c) 'SlsUndyedKrsnUseBusGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-017-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnUsedInAvnTxd219CrAmt"), hasNonZero("SlsKrsnUsedInAvnTxd219GalsQty")),
    "If Form 4136, Line 8a(d) 'SlsKrsnUsedInAvnTxd219CrAmt' has a non-zero value, then Line 8a(c) 'SlsKrsnUsedInAvnTxd219GalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-018-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnUsedInAvnTxd244CrAmt"), hasNonZero("SlsKrsnUsedInAvnTxd244GalsQty")),
    "If Form 4136, Line 8b(d) 'SlsKrsnUsedInAvnTxd244CrAmt' has a non-zero value, then Line 8b(c) 'SlsKrsnUsedInAvnTxd244GalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-019-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnNnxmptUseInAvnCrAmt"), hasNonZero("SlsKrsnNnxmptUseInAvnGalsQty")),
    "If Form 4136, Line 8c(d) 'SlsKrsnNnxmptUseInAvnCrAmt' has a non-zero value, then Line 8c(c) 'SlsKrsnNnxmptUseInAvnGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-020-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnOthNontxTxd244CrAmt"), hasNonZero("SlsKrsnOthNontxTxd244_GallonsQty")),
    "If Form 4136, Line 8d(d) 'SlsKrsnOthNontxTxd244CrAmt' has a non-zero value, then Line 8d(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-021-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnOthNontxTxd219CrAmt"), hasNonZero("SlsKrsnOthNontxTxd219_GallonsQty")),
    "If Form 4136, Line 8e(d) 'SlsKrsnOthNontxTxd219CrAmt' has a non-zero value, then Line 8e(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-024-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("BiodieselMixtureCreditAmt"), hasNonZero("BiodieselMixtureGallonsQty")),
    "If Form 4136, Line 10a(d) 'BiodieselMixtureCreditAmt' has a non-zero value, then Line 10a(c) 'BiodieselMixtureGallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-025-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("AgriBiodieselMixtureCreditAmt"), hasNonZero("AgriBiodieselMixtureGallonsQty")),
    "If Form 4136, Line 10b(d) 'AgriBiodieselMixtureCreditAmt' has a non-zero value, then Line 10b(c) 'AgriBiodieselMixtureGallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-026-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("RenewableDieselMixtureCrAmt"), hasNonZero("RenewableDieselMixtureGalsQty")),
    "If Form 4136, Line 10c(d) 'RenewableDieselMixtureCrAmt' has a non-zero value, then Line 10c(c) 'RenewableDieselMixtureGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-033-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedPetroleumGasCrAmt"), hasNonZero("LiquefiedPetroleumGasGalsQty")),
    "If Form 4136, Line 12a(d) 'LiquefiedPetroleumGasCrAmt' has a non-zero value, then Line 12a(c) 'LiquefiedPetroleumGasGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-034-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("CompressedNaturalGasCreditAmt"), hasNonZero("CompressedNaturalGasGalsQty")),
    "If Form 4136, Line 12c(d) 'CompressedNaturalGasCreditAmt' has a non-zero value, then Line 12c(c) 'CompressedNaturalGasGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-035-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("PSeriesFuelsCreditAmt"), hasNonZero("PSeriesFuelsGallonsQty")),
    "If Form 4136, Line 12b(d) 'PSeriesFuelsCreditAmt' has a non-zero value, then Form 12b(c) 'PSeriesFuelsGallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-036-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedHydrogenCreditAmt"), hasNonZero("LiquefiedHydrogenGallonsQty")),
    "If Form 4136, Line 12d(d) 'LiquefiedHydrogenCreditAmt' has a non-zero value, then Line 12d(c) 'LiquefiedHydrogenGallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-037-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquidFuelDerFromCoalCreditAmt"), hasNonZero("LiquidFuelDerFromCoalGalsQty")),
    "If Form 4136, Line 12e(d) 'LiquidFuelDerFromCoalCreditAmt' has a non-zero value, then Line 12e(c) 'LiquidFuelDerFromCoalGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-038-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquidFuelDerBiomassCrAmt"), hasNonZero("LiquidFuelDerBiomassGalsQty")),
    "If Form 4136, Line 12f(d) 'LiquidFuelDerBiomassCrAmt' has a non-zero value, then Line 12f(c) 'LiquidFuelDerBiomassGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-039-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedNaturalGasCreditAmt"), hasNonZero("LiquefiedNaturalGasGallonsQty")),
    "If Form 4136, Line 12g(d) 'LiquefiedNaturalGasCreditAmt' has a non-zero value, then Line 12g(c) 'LiquefiedNaturalGasGallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-040-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("DslFuelSoldStLocalGovtCrAmt"), hasNonZero("DslFuelSoldStLocalGovtGalsQty")),
    "If Form 4136, Line 13a(d) 'DslFuelSoldStLocalGovtCrAmt' has a non-zero value, then 13a(c) 'DslFuelSoldStLocalGovtGalsQty' must have a non-zero value",
  ),
  rule(
    "F4136-041-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("KrsnFuelSoldStLocalGovtCrAmt"), hasNonZero("KrsnFuelSoldStLocalGovtGalsQty")),
    "If Form 4136, Line 13b(d) 'KrsnFuelSoldStLocalGovtCrAmt' has a non-zero value, then Line 13b(c) 'KrsnFuelSoldStLocalGovtGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-043-03",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxUseDieselWtrEmulsionCrAmt"), any(hasNonZero("NontxUseDieselWaterEmulsion_GallonsQty"), hasNonZero("BusNontxUseDieselWtrEmulsion_GallonsQty"))),
    "If Form 4136, Line 14a(d) 'NontxUseDieselWtrEmulsionCrAmt' has a non-zero value, then Line 14a(c) 'GallonsQty' in 'NontxUseDieselWaterEmulsion' or Line 14a(c) 'GallonsQty' in 'BusNontxUseDieselWtrEmulsion' must have a non-zero value.",
  ),
  rule(
    "F4136-045-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("BlndrCrUseDslWtrEmulsionCrAmt"), hasNonZero("BlndrCrUseDslWtrEmulsionQty")),
    "If Form 4136, Line 15(d) 'BlndrCrUseDslWtrEmulsionCrAmt' has a non-zero value, then Line 15(c) 'BlndrCrUseDslWtrEmulsionQty' must have a non-zero value.",
  ),
  rule(
    "F4136-046-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("ExportedDyedDieselFuelCrAmt"), hasNonZero("ExportedDyedDieselFuelGalsQty")),
    "If Form 4136, Line 16a(d) 'ExportedDyedDieselFuelCrAmt' has a non-zero value, then Line 16a(c) 'ExportedDyedDieselFuelGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-047-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("ExportedDyedKeroseneCreditAmt"), hasNonZero("ExportedDyedKeroseneGallonsQty")),
    "If Form 4136, Line 16b(d) 'ExportedDyedKeroseneCreditAmt' has a non-zero value, then Line 16b(c) 'ExportedDyedKeroseneGallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-048-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LUSTTxAvnFuelFrgnTradeCrAmt"), hasNonZero("LUSTTxAvnFuelFrgnTradeGalsQty")),
    "If Form 4136, Line 2d(d) 'LUSTTxAvnFuelFrgnTradeCrAmt' has a non-zero value, then Line 2d(c) 'LUSTTxAvnFuelFrgnTradeGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-049-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LUSTTxKrsnAvnFrgnTrdCrAmt"), hasNonZero("LUSTTxKrsnAvnFrgnTrdGalsQty")),
    "If Form 4136, Line 5e(d) 'LUSTTxKrsnAvnFrgnTrdCrAmt' has a non-zero value, then Line 5e(c) 'LUSTTxKrsnAvnFrgnTrdGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-050-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedGasDerBiomassCrAmt"), hasNonZero("LiquefiedGasDerBiomassGalsQty")),
    "If Form 4136, Line 12h(d) 'LiquefiedGasDerBiomassCrAmt' has a non-zero value, then Line 12h(c) 'LiquefiedGasDerBiomassGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-051-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("CompressedGasBiomassCreditAmt"), hasNonZero("CompressedGasBiomassGGEQty")),
    "If Form 4136, Line 12i(d) 'CompressedGasBiomassCreditAmt' has a non-zero value, then Line 12i(c) 'CompressedGasBiomassGGEQty' must have a non-zero value.",
  ),
  rule(
    "F4136-052-01",
    "reject",
    "missing_data",
    alwaysPass, // requires checking for attached explanation statement
    "If Form 4136, Line 3 'UndyedDieselUseExceptionInd' checkbox is checked, then \"Evidence of Dyed Diesel Fuel Explanation Statement\" [EvidenceOfDyedDieselFuelStatement], must be attached to Line 3.",
  ),
  rule(
    "F4136-053-01",
    "reject",
    "missing_data",
    alwaysPass, // requires checking for attached explanation statement
    "If Form 4136, Line 4 'UndyedKeroseneUseExceptionInd' checkbox is checked, then \"Evidence of Dyed Kerosene Explanation Statement\" [EvidenceOfDyedKeroseneStatement], must be attached.",
  ),
  rule(
    "F4136-054-01",
    "reject",
    "missing_data",
    alwaysPass, // requires checking for attached explanation statement
    "If Form 4136, Line 6 'SalesUndyedDieselExceptionInd' checkbox is checked, then \"Evidence of Dyed Diesel Fuel Sold Explanation Statement\" [EvidenceOfDyedDieselFuelSoldStatement] or \"To Whom Diesel Fuel Sold Statement\" [ToWhomDieselFuelSoldStatement] must be attached to Line 6.",
  ),
  rule(
    "F4136-055-01",
    "reject",
    "missing_data",
    alwaysPass, // requires checking for attached explanation statement
    "If Form 4136, Line 7 'SlsUndyedKeroseneExceptionInd' checkbox is checked, then \"Evidence of Dyed Kerosene Sold Explanation Statement\" [EvidenceOfDyedKeroseneSoldStmt] must be attached to Line 7.",
  ),
  rule(
    "F4136-056-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsUndyedDslUseStLclGovtCrAmt"), hasValue("UndyedDieselRegistrationNum")),
    "If Form 4136, Line 6a(d) 'SlsUndyedDslUseStLclGovtCrAmt' has a non-zero value, then Line 6 'UndyedDieselRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-057-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsUndyedDieselUseBusCrAmt"), hasValue("UndyedDieselRegistrationNum")),
    "If Form 4136, Line 6b(d) 'SlsUndyedDieselUseBusCrAmt' has a non-zero value, then Line 6 'UndyedDieselRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-058-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsUndyedKrsnBlockPumpCrAmt"), hasValue("UndyedKeroseneRegistrationNum")),
    "If Form 4136, Line 7b(d) 'SlsUndyedKrsnBlockPumpCrAmt' has a non-zero value, then Line 7 'UndyedKeroseneRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-059-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsUndyedKrsnUseBusCrAmt"), hasValue("UndyedKeroseneRegistrationNum")),
    "If Form 4136, Line 7c(d) 'SlsUndyedKrsnUseBusCrAmt' has a non-zero value, then Line 7 'UndyedKeroseneRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-060-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnUsedInAvnTxd219CrAmt"), hasValue("KeroseneForAvnRegistrationNum")),
    "If Form 4136, Line 8a(d) 'SlsKrsnUsedInAvnTxd219CrAmt' has a non-zero value then, Line 8 'KeroseneForAvnRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-061-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnUsedInAvnTxd244CrAmt"), hasValue("KeroseneForAvnRegistrationNum")),
    "If Form 4136, Line 8b(d) 'SlsKrsnUsedInAvnTxd244CrAmt' has a non-zero value then, Line 8 'KeroseneForAvnRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-062-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnNnxmptUseInAvnCrAmt"), hasValue("KeroseneForAvnRegistrationNum")),
    "If Form 4136, Line 8c(d) 'SlsKrsnNnxmptUseInAvnCrAmt' has a non-zero value then, Line 8 'KeroseneForAvnRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-063-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnOthNontxTxd244CrAmt"), hasValue("KeroseneForAvnRegistrationNum")),
    "If Form 4136, Line 8d(d) 'SlsKrsnOthNontxTxd244CrAmt' has a non-zero value then, Line 8 'KeroseneForAvnRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-064-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsKrsnOthNontxTxd219CrAmt"), hasValue("KeroseneForAvnRegistrationNum")),
    "If Form 4136, Line 8e(d) 'SlsKrsnOthNontxTxd219CrAmt' has a non-zero value then, Line 8 'KeroseneForAvnRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-065-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NonTxKrsnUsedInAvnTxd244CrAmt"), hasNonZero("NonTxKrsnUsedInAvnTxd244_GallonsQty")),
    "If Form 4136, Line 5c(d) 'NonTxKrsnUsedInAvnTxd244CrAmt' has a non-zero value, then Line 5c(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-066-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NonTxKrsnUsedInAvnTxd219CrAmt"), hasNonZero("NonTxKrsnUsedInAvnTxd219_GallonsQty")),
    "If Form 4136, Line 5d(d) 'NonTxKrsnUsedInAvnTxd219CrAmt' has a non-zero value, then Line 5d(c) 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-069-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("BiodieselMixtureCreditAmt"), hasValue("BiodieselRnwblRegistrationNum")),
    "If Form 4136, Line 10a(d) 'BiodieselMixtureCreditAmt' has a non-zero value, then Line 10 'BiodieselRnwblRegistrationNum' must contain a value.",
  ),
  rule(
    "F4136-070-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("AgriBiodieselMixtureCreditAmt"), hasValue("BiodieselRnwblRegistrationNum")),
    "If Form 4136, Line 10b(d) 'AgriBiodieselMixtureCreditAmt' has a non-zero value, then Line 10 'BiodieselRnwblRegistrationNum' must contain a value.",
  ),
  rule(
    "F4136-071-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("RenewableDieselMixtureCrAmt"), hasValue("BiodieselRnwblRegistrationNum")),
    "If Form 4136, Line 10c(d) 'RenewableDieselMixtureCrAmt' has a non-zero value, then Line 10 'BiodieselRnwblRegistrationNum' must contain a value.",
  ),
  rule(
    "F4136-072-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedPetroleumGasCrAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12a(d) 'LiquefiedPetroleumGasCrAmt' has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-073-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("PSeriesFuelsCreditAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12b(d) 'PSeriesFuelsCreditAmt' has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-074-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("CompressedNaturalGasCreditAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12c(d) 'CompressedNaturalGasCreditAmt' has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-075-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedHydrogenCreditAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12d(d) 'LiquefiedHydrogenCreditAmt' has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-076-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquidFuelDerFromCoalCreditAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12e (d) 'LiquidFuelDerFromCoalCreditAmt' has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-077-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquidFuelDerBiomassCrAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12f (d) 'LiquidFuelDerBiomassCrAmt', has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-078-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedNaturalGasCreditAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12g (d) 'LiquefiedNaturalGasCreditAmt', has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-079-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LiquefiedGasDerBiomassCrAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12h (d) 'LiquefiedGasDerBiomassCrAmt', has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-080-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("CompressedGasBiomassCreditAmt"), hasValue("AlternativeFuelRegistrationNum")),
    "If Form 4136, Line 12i (d) 'CompressedGasBiomassCreditAmt', has a non-zero value, then Line 12 'AlternativeFuelRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-081-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("DslFuelSoldStLocalGovtCrAmt"), hasValue("CreditCardIssrRegistrationNum")),
    "If Form 4136, Line 13a(d) 'DslFuelSoldStLocalGovtCrAmt' has a non-zero value, then Line 13 'CreditCardIssrRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-082-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("KrsnFuelSoldStLocalGovtCrAmt"), hasValue("CreditCardIssrRegistrationNum")),
    "If Form 4136, Line 13b(d) 'KrsnFuelSoldStLocalGovtCrAmt' has a non-zero value, then Line 13 'CreditCardIssrRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-083-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("KrsnAvnSoldStLocalGovtCrAmt"), hasValue("CreditCardIssrRegistrationNum")),
    "If Form 4136, Line 13c(d) 'KrsnAvnSoldStLocalGovtCrAmt' has a non-zero value, then Line 13 'CreditCardIssrRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-084-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("BlndrCrUseDslWtrEmulsionCrAmt"), hasValue("DieselWtrBlndgRegistrationNum")),
    "If Form 4136, Line 15(d) 'BlndrCrUseDslWtrEmulsionCrAmt' has a non-zero value, then Line 15 'DieselWtrBlndgRegistrationNum' must have a value.",
  ),
  rule(
    "F4136-085-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("ExportedNontxUseOfGasCrAmt"), hasNonZero("ExportedNontxUseGasGalsQty")),
    "If Form 4136, Line 1d(d) 'ExportedNontxUseOfGasCrAmt' has a non-zero value, then Form 4136 Line 1d(c) 'ExportedNontxUseGasGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-086-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("ExpNontxAviationGasCrAmt"), hasNonZero("ExpNontxAviationGasGalsQty")),
    "If Form 4136, Line 2c(d) 'ExpNontxAviationGasCrAmt' has a non-zero value, then Form 4136 Line 2c(c) 'ExpNontxAviationGasGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-087-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("KeroseneUsedInAvnTxd244CrAmt"), hasNonZero("KeroseneUsedInAvnTxd244GalsQty")),
    "If Form 4136, Line 5a(d) 'KeroseneUsedInAvnTxd244CrAmt' has a non-zero value, then Form 4136 Line 5a(c) 'KeroseneUsedInAvnTxd244GalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-088-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxLiqfdFuelDerFromCoalCrAmt"), any(hasNonZero("NontxLiqfdFuelDerivedFromCoal_GallonsQty"), hasNonZero("BusNontxLiqfdFuelDerFromCoal_GallonsQty"))),
    "If Form 4136, Line 11e(d) 'NontxLiqfdFuelDerFromCoalCrAmt' has a non-zero value, then line 11e(c) 'GallonsQty' in 'NontxLiqfdFuelDerivedFromCoal' or Line 11e(c) 'GallonsQty' in 'BusNontxLiqfdFuelDerFromCoal' must have a non-zero value.",
  ),
  rule(
    "F4136-089-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("KrsnAvnSoldStLocalGovtCrAmt"), hasNonZero("KrsnAvnSoldStLocalGovtGalsQty")),
    "If Form 4136, Line 13c(d) 'KrsnAvnSoldStLocalGovtCrAmt' has a non-zero value, then Line 13c(c) 'KrsnAvnSoldStLocalGovtGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-090-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("LUSTTxSlsKrsnAvnFrgnTrdCrAmt"), hasNonZero("LUSTTxSlsKrsnAvnFrgnTrdGalsQty")),
    "If Form 4136, Line 8f(d) 'LUSTTxSlsKrsnAvnFrgnTrdCrAmt' has a non-zero value, then Line 8f(c) 'LUSTTxSlsKrsnAvnFrgnTrdGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-091-03",
    "reject",
    "missing_data",
    alwaysPass, // requires summing all Lines 1c(d) through 16b(d) — too many addends for static enumeration
    "Form 4136, Line 17 'TotalFuelTaxCreditAmt' must equal the sum of Lines 1c(d) through Lines 16b(d).",
  ),
  rule(
    "F4136-092-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxLiquefiedPtrlmGasCrAmt"), any(hasNonZero("NontxLiquifiedPetroleumGas_GallonsQty"), hasNonZero("BusNontxLiquifiedPetroleumGas_GallonsQty"))),
    "If Form 4136, Line 11a(d) 'NontxLiquefiedPtrlmGasCrAmt' has a non-zero value, then Line 11a(c) 'GallonsQty' in 'NontxLiquifiedPetroleumGas' or Line 11a(c) 'GallonsQty' in 'BusNontxLiquifiedPetroleumGas' must have a non-zero value.",
  ),
  rule(
    "F4136-093-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("FarmPrpsUndyedDslFuelCrAmt"), any(hasNonZero("NontaxableUseOfUndyedDiesel_GallonsQty"), hasNonZero("FarmPrpsUndyedDslFuelGalsQty"))),
    "If Form 4136, Line 3b(d) 'FarmPrpsUndyedDslFuelCrAmt' has a non-zero value, then Line 3a(c) 'GallonsQty' in 'NontaxableUseOfUndyedDiesel' or Line 3b(c) 'FarmPrpsUndyedDslFuelGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-094-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("FarmPrpsUndyedKeroseneCrAmt"), any(hasNonZero("NontaxableUseOfUndyedKerosene_GallonsQty"), hasNonZero("FarmPrpsUndyedKeroseneGalsQty"))),
    "If Form 4136, Line 4b(d) 'FarmPrpsUndyedKeroseneCrAmt' has a non-zero value, then Line 4a(c) 'GallonsQty' in 'NontaxableUseOfUndyedKerosene' or Line 4b(c) 'FarmPrpsUndyedKeroseneGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-095-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SlsUndyedKrsnBlockPumpCrAmt"), any(hasNonZero("SlsUndyedKrsnStLclGovtGalsQty"), hasNonZero("SlsUndyedKrsnBlockPumpGalsQty"))),
    "If Form 4136, Line 7b(d) 'SlsUndyedKrsnBlockPumpCrAmt' has a non-zero value, then Line 7a(c) 'SlsUndyedKrsnStLclGovtGalsQty' or Line 7b(c) 'SlsUndyedKrsnBlockPumpGalsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-096-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxPSeriesFuelsCreditAmt"), any(hasNonZero("NontxPSeriesFuels_GallonsQty"), hasNonZero("BusNontxPSeriesFuels_GallonsQty"))),
    "If Form 4136, Line 11b(d) 'NontxPSeriesFuelsCreditAmt' has a non-zero value, then Line 11b(c) 'GallonsQty' in 'NontxPSeriesFuels' or Line 11b(c) 'GallonsQty' in 'BusNontxPSeriesFuels' must have a non-zero value.",
  ),
  rule(
    "F4136-097-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxCompressedNaturalGasCrAmt"), any(hasNonZero("NontxCompressedNaturalGas_GallonsQty"), hasNonZero("BusNontxCompressedNaturalGas_GallonsQty"))),
    "If Form 4136, Line 11c(d) 'NontxCompressedNaturalGasCrAmt' has a non-zero value, then Line 11c(c) 'GallonsQty' in 'NontxCompressedNaturalGas' or Line 11 c(c) 'GallonsQty' in 'BusNontxCompressedNaturalGas' must have a non-zero value.",
  ),
  rule(
    "F4136-098-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxLiquefiedHydrogenCrAmt"), any(hasNonZero("NontxLiquifiedHydrogen_GallonsQty"), hasNonZero("BusNontxLiquifiedHydrogen_GallonsQty"))),
    "If Form 4136, Line 11d(d) 'NontxLiquefiedHydrogenCrAmt' has a non-zero value, then Line 11d(c) 'GallonsQty' in 'NontxLiquifiedHydrogen' or Line 11d(c) 'GallonsQty' in 'BusNontxLiquifiedHydrogen' must have a non-zero value.",
  ),
  rule(
    "F4136-099-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxLiqFuelDerBiomassCrAmt"), any(hasNonZero("NontaxLiqFuelDerFromBiomass_GallonsQty"), hasNonZero("BusNontxLiqFuelDerFromBiomass_GallonsQty"))),
    "If Form 4136, Line 11f(d) 'NontxLiqFuelDerBiomassCrAmt' has a non-zero value, then Line 11f(c) 'GallonsQty' in 'NontaxLiqFuelDerFromBiomass' or Line 11f(c) 'GallonsQty' in 'BusNontxLiqFuelDerFromBiomass' must have a non-zero value.",
  ),
  rule(
    "F4136-100-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxLiquefiedNaturalGasCrAmt"), any(hasNonZero("NontxLiquefiedNaturalGas_GallonsQty"), hasNonZero("BusNontxLiquefiedNaturalGas_GallonsQty"))),
    "If Form 4136, Line 11g(d) 'NontxLiquefiedNaturalGasCrAmt' has a non-zero value, then Line 11g(c) 'GallonsQty' in 'NontxLiquefiedNaturalGas' or Line 11g(c) 'GallonsQty' in 'BusNontxLiquefiedNaturalGas' must have a non-zero value.",
  ),
  rule(
    "F4136-101-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NontxLiquefiedGasBiomassCrAmt"), any(hasNonZero("NontxLiquefiedGasBiomass_GallonsQty"), hasNonZero("BusNontxLiquefiedGasDerBiomass_GallonsQty"))),
    "If Form 4136, Line 11h(d) 'NontxLiquefiedGasBiomassCrAmt' has a non-zero value, then Line 11h(c) 'GallonsQty' in 'NontxLiquefiedGasBiomass' or Line 11h(c) 'GallonsQty' in 'BusNontxLiquefiedGasDerBiomass' must have a non-zero value.",
  ),
  rule(
    "F4136-130",
    "reject",
    "incorrect_data",
    isZero("LiquefiedHydrogenCreditAmt"),
    "Form 4136, Line 12d(d) 'LiquefiedHydrogenCreditAmt' must be equal to zero if an amount is entered.",
  ),
  rule(
    "F4136-131",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SustainableAviationFuelCrAmt"), hasNonZero("SustainableAviationFuelDetail_GallonsQty")),
    "If Form 4136 'SustainableAviationFuelCrAmt' has a non-zero value, then Sustainable Aviation Fuel Detail 'GallonsQty' must have a non-zero value.",
  ),
  rule(
    "F4136-132",
    "reject",
    "missing_data",
    ifThen(hasNonZero("SustainableAviationFuelCrAmt"), hasValue("BiodieselRnwblRegistrationNum")),
    "If Form 4136 'SustainableAviationFuelCrAmt' has a non-zero value, then 'BiodieselRnwblRegistrationNum' must contain a value.",
  ),
];
