/**
 * MeF Business Rules: F5471
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 29 rules (29 implemented, 0 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, all, any, eqStr, formPresent, gte, hasNonZero, hasValue, ifThen, noValue, } from "../../../../core/validation/mod.ts";

export const F5471_RULES: readonly RuleDef[] = [
  rule(
    "F5471-045-01",
    "reject",
    "incorrect_data",
    all(
      ifThen(hasValue("BegngAcctPrdBadDebtAllwncAmt"), gte("BegngAcctPrdBadDebtAllwncAmt", 0)),
      ifThen(hasValue("EndAcctPrdBadDebtAllwncAmt"), gte("EndAcctPrdBadDebtAllwncAmt", 0)),
      ifThen(hasValue("BegngAcctPrdNetAccumDeprecAmt"), gte("BegngAcctPrdNetAccumDeprecAmt", 0)),
      ifThen(hasValue("EndAcctPrdNetAccumDeprecAmt"), gte("EndAcctPrdNetAccumDeprecAmt", 0)),
      ifThen(hasValue("BegngAcctPrdNetAccumDpltnAmt"), gte("BegngAcctPrdNetAccumDpltnAmt", 0)),
      ifThen(hasValue("EndAcctPrdNetAccumDpltnAmt"), gte("EndAcctPrdNetAccumDpltnAmt", 0)),
      ifThen(hasValue("BegngAcctPrdNetAccumAmortzAmt"), gte("BegngAcctPrdNetAccumAmortzAmt", 0)),
      ifThen(hasValue("EndAcctPrdNetAccumAmortzAmt"), gte("EndAcctPrdNetAccumAmortzAmt", 0)),
      ifThen(hasValue("BegngAcctPrdNetCostOfTrStkAmt"), gte("BegngAcctPrdNetCostOfTrStkAmt", 0)),
      ifThen(hasValue("EndAcctPrdNetCostOfTrStkAmt"), gte("EndAcctPrdNetCostOfTrStkAmt", 0)),
    ),
    "Form 5471, Schedule F, Line 2b(a) 'BegngAcctPrdBadDebtAllwncAmt', Line 2b(b) 'EndAcctPrdBadDebtAllwncAmt', Line 8b(a) 'BegngAcctPrdNetAccumDeprecAmt', Line 8b(b) 'EndAcctPrdNetAccumDeprecAmt', Line 9b(a) 'BegngAcctPrdNetAccumDpltnAmt', Line 9b(b) 'EndAcctPrdNetAccumDpltnAmt', Line 11d(a) 'BegngAcctPrdNetAccumAmortzAmt', Line 11d(b) 'EndAcctPrdNetAccumAmortzAmt', Line 21a 'BegngAcctPrdNetCostOfTrStkAmt', Line 21b 'EndAcctPrdNetCostOfTrStkAmt' must not have a value less than zero.",
  ),
  rule(
    "F5471-046-01",
    "reject",
    "missing_document",
    ifThen(hasValue("CategoryOfFiler3"), hasValue("Category3FilerStatement")),
    "If Form 5471, Line B(3) 'CategoryOfFiler3' checkbox is checked, then \"Category 3 Filer Statement\" [Category3FilerStatement] must be attached to Line B (3).",
  ),
  rule(
    "F5471-047-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("ForeignOtherIncomeAmt"), hasValue("OtherIncomeForm5471Statement")),
    "If Form 5471, Schedule C, 'ForeignOtherIncomeAmt' has a non-zero value, then [OtherIncomeForm5471Statement] must be attached to 'ForeignOtherIncomeAmt'.",
  ),
  rule(
    "F5471-048-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("USOtherIncomeAmt"), hasValue("OtherIncomeForm5471Statement")),
    "If Form 5471, Schedule C, 'USOtherIncomeAmt' has a non-zero value, then [OtherIncomeForm5471Statement] must be attached to 'USOtherIncomeAmt'.",
  ),
  rule(
    "F5471-049-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("ForeignOtherDeductionsAmt"), hasValue("ItemizedOtherDeductionsSchedule2")),
    "If Form 5471, Schedule C, 'ForeignOtherDeductionsAmt' has a non-zero value, then [ItemizedOtherDeductionsSchedule2] must be attached to 'ForeignOtherDeductionsAmt'.",
  ),
  rule(
    "F5471-050-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("USOtherDeductionsAmt"), hasValue("ItemizedOtherDeductionsSchedule2")),
    "If Form 5471, Schedule C, 'USOtherDeductionsAmt' has a non-zero value, then [ItemizedOtherDeductionsSchedule2] must be attached to 'USOtherDeductionsAmt'.",
  ),
  rule(
    "F5471-051-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("BegngAcctPrdOtherCurrAssetsAmt"), hasValue("ItemizedOtherCurrentAssetsSchedule")),
    "If Form 5471, Schedule F, 'BegngAcctPrdOtherCurrAssetsAmt' has a non-zero value, then [ItemizedOtherCurrentAssetsSchedule] must be attached to 'BegngAcctPrdOtherCurrAssetsAmt'.",
  ),
  rule(
    "F5471-052-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("EndAcctPrdOtherCurrAssetsAmt"), hasValue("ItemizedOtherCurrentAssetsSchedule")),
    "If Form 5471, Schedule F, 'EndAcctPrdOtherCurrAssetsAmt' has a non-zero value, then [ItemizedOtherCurrentAssetsSchedule] must be attached to 'EndAcctPrdOtherCurrAssetsAmt'.",
  ),
  rule(
    "F5471-053-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("BegngAcctPrdInvstSubsidiaryAmt"), hasValue("InvestmentInSubsidiariesStmt")),
    "If Form 5471, Schedule F, 'BegngAcctPrdInvstSubsidiaryAmt' has a non-zero value, then [InvestmentInSubsidiariesStmt] must be attached to 'BegngAcctPrdInvstSubsidiaryAmt'.",
  ),
  rule(
    "F5471-054-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("EndAcctPrdInvstSubsidiaryAmt"), hasValue("InvestmentInSubsidiariesStmt")),
    "If Form 5471, Schedule F, 'EndAcctPrdInvstSubsidiaryAmt' has a non-zero value, then [InvestmentInSubsidiariesStmt] must be attached to 'EndAcctPrdInvstSubsidiaryAmt'.",
  ),
  rule(
    "F5471-055-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("BegngAcctPrdOthInvestmentsAmt"), hasValue("ItemizedOtherInvestmentsSchedule")),
    "If Form 5471, Schedule F, 'BegngAcctPrdOthInvestmentsAmt' has a non-zero value, then [ItemizedOtherInvestmentsSchedule] must be attached to 'BegngAcctPrdOthInvestmentsAmt'.",
  ),
  rule(
    "F5471-056-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("EndAcctPrdOthInvestmentsAmt"), hasValue("ItemizedOtherInvestmentsSchedule")),
    "If Form 5471, Schedule F, 'EndAcctPrdOthInvestmentsAmt' has a non-zero value, then [ItemizedOtherInvestmentsSchedule] must be attached to 'EndAcctPrdOthInvestmentsAmt'.",
  ),
  rule(
    "F5471-057-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("BegngAcctPrdOtherAssetsAmt"), hasValue("ItemizedOtherAssetsSchedule")),
    "If Form 5471, Schedule F, 'BegngAcctPrdOtherAssetsAmt' has a non-zero value, then [ItemizedOtherAssetsSchedule] must be attached to 'BegngAcctPrdOtherAssetsAmt'.",
  ),
  rule(
    "F5471-058-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("EndAcctPrdOtherAssetsAmt"), hasValue("ItemizedOtherAssetsSchedule")),
    "If Form 5471, Schedule F, 'EndAcctPrdOtherAssetsAmt' has a non-zero value, then [ItemizedOtherAssetsSchedule] must be attached to 'EndAcctPrdOtherAssetsAmt'.",
  ),
  rule(
    "F5471-059-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("BegngAcctPrdOtherCurrLiabAmt"), hasValue("ItemizedOtherCurrentLiabilitiesSchedule")),
    "If Form 5471, Schedule F, 'BegngAcctPrdOtherCurrLiabAmt' has a non-zero value, then [ItemizedOtherCurrentLiabilitiesSchedule] must be attached to 'BegngAcctPrdOtherCurrLiabAmt'.",
  ),
  rule(
    "F5471-060-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("EndAcctPrdOtherCurrLiabAmt"), hasValue("ItemizedOtherCurrentLiabilitiesSchedule")),
    "If Form 5471, Schedule F, 'EndAcctPrdOtherCurrLiabAmt' has a non-zero value, then [ItemizedOtherCurrentLiabilitiesSchedule] must be attached to 'EndAcctPrdOtherCurrLiabAmt'.",
  ),
  rule(
    "F5471-061-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("BegngAcctPrdOthLiabilitiesAmt"), hasValue("ItemizedOtherLiabilitiesSchedule")),
    "If Form 5471, Schedule F, 'BegngAcctPrdOthLiabilitiesAmt' has a non-zero value, then [ItemizedOtherLiabilitiesSchedule] must be attached to 'BegngAcctPrdOthLiabilitiesAmt'.",
  ),
  rule(
    "F5471-062-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("EndAcctPrdOthLiabilitiesAmt"), hasValue("ItemizedOtherLiabilitiesSchedule")),
    "If Form 5471, Schedule F, 'EndAcctPrdOthLiabilitiesAmt' has a non-zero value, then [ItemizedOtherLiabilitiesSchedule] must be attached to 'EndAcctPrdOthLiabilitiesAmt'.",
  ),
  rule(
    "F5471-063-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("BegngAcctPrdPaidInOrSurplusAmt"), hasValue("PaidInOrCapSurplusRecnclStmt")),
    "If Form 5471, Schedule F, 'BegngAcctPrdPaidInOrSurplusAmt' has a non-zero value, then [PaidInOrCapSurplusRecnclStmt] must be attached to 'BegngAcctPrdPaidInOrSurplusAmt'.",
  ),
  rule(
    "F5471-064-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("EndAcctPrdPaidInOrSurplusAmt"), hasValue("PaidInOrCapSurplusRecnclStmt")),
    "If Form 5471, Schedule F, 'EndAcctPrdPaidInOrSurplusAmt' has a non-zero value, then [PaidInOrCapSurplusRecnclStmt] must be attached to 'EndAcctPrdPaidInOrSurplusAmt'.",
  ),
  rule(
    "F5471-065-01",
    "reject",
    "missing_document",
    ifThen(eqStr("Owns10PctOrMoreFrgnPrtshpInd", "Yes"), hasValue("OwnsForeignPartnershipStmt")),
    "If Form 5471, Schedule G, Line 1 'Owns10PctOrMoreFrgnPrtshpInd' has a choice of \"Yes\" indicated, then\"Owns Foreign Partnership Statement\" [OwnsForeignPartnershipStmt] must be attached to Schedule G, Line 1.",
  ),
  rule(
    "F5471-066-02",
    "reject",
    "missing_data",
    ifThen(eqStr("FrgnCorpOwnsForeignEntityInd", "Yes"), any(hasValue("OwnsForeignEntitiesStatement"), formPresent("form8858"), eqStr("Form8858PaperDocumentInd", "Yes"))),
    "If Form 5471, Schedule G, Line 3 'FrgnCorpOwnsForeignEntityInd' has a choice of \"Yes\" indicated, then \"Owns Foreign Entities Statement\" [OwnsForeignEntitiesStatement] or Form 8858 must be attached to Schedule G, Line 3 or the 'Form8858PaperDocumentInd' in the Return Header must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "F5471-069-01",
    "reject",
    "missing_document",
    ifThen(eqStr("IncomeBlockedInd", "Yes"), hasValue("ExplanationOfBlockedIncomeStmt")),
    "If Form 5471, Schedule I, 'IncomeBlockedInd' has a choice of \"Yes\" indicated, then \"Explanation Of Blocked Income Statement\" [ExplanationOfBlockedIncomeStmt] must be attached to Schedule I, 'IncomeBlockedInd'.",
  ),
  rule(
    "F5471-070-01",
    "reject",
    "missing_document",
    ifThen(eqStr("IncomeUnblockedInd", "Yes"), hasValue("ExplanationOfBlockedIncomeStmt")),
    "If Form 5471, Schedule I, 'IncomeUnblockedInd' has a choice of \"Yes\" indicated, then \"Explanation Of Blocked Income Statement\" [ExplanationOfBlockedIncomeStmt] must be attached to Schedule I, 'IncomeUnblockedInd'.",
  ),
  rule(
    "F5471-071-01",
    "reject",
    "missing_data",
    any(hasValue("EmployerEIN"), hasValue("ForeignEntityReferenceIdNum")),
    "Form 5471 'EmployerEIN' or 'ForeignEntityReferenceIdNum' must have a value.",
  ),
  rule(
    "F5471-072",
    "reject",
    "missing_document",
    ifThen(all(noValue("dormantForeignCorporationCd"), hasNonZero("OtherAdjustmentsNetAddnAmt")), hasValue("EarningsAndProfitsOtherAdjStmt")),
    "If Form 5471, 'dormantForeignCorporationCd' is not present in the Return, and Form 5471, Schedule H, 'OtherAdjustmentsNetAddnAmt' has a non-zero value, then 'EarningsAndProfitsOtherAdjStmt' must be attached to 'OtherAdjustmentsNetAddnAmt'.",
  ),
  rule(
    "F5471-073",
    "reject",
    "missing_document",
    ifThen(all(noValue("dormantForeignCorporationCd"), hasNonZero("OtherAdjustmentsNetSbtrctnAmt")), hasValue("EarningsAndProfitsOtherAdjStmt")),
    "If Form 5471, 'dormantForeignCorporationCd' is not present in the Return, and Form 5471, Schedule H, 'OtherAdjustmentsNetSbtrctnAmt' has a non-zero value, then 'EarningsAndProfitsOtherAdjStmt' must be attached to 'OtherAdjustmentsNetSbtrctnAmt'.",
  ),
  rule(
    "F5471-074",
    "reject",
    "missing_document",
    ifThen(hasValue("CorrectedInd"), all(hasValue("FormOrSchChgExplnStmt"), eqStr("ScheduleOrFormNum", "5471"))),
    "If Form 5471 'CorrectedInd' is check, then 'FormOrSchChgExplnStmt' must be present and 'ScheduleOrFormNum' must have the value of \"5471\".",
  ),
  rule(
    "F5471-076",
    "reject",
    "missing_data",
    ifThen(eqStr("FrgnCorpPartcpCostShrInd", "Yes"), formPresent("scheduleG1Form5471")),
    "If Form 5471, Schedule G, 'FrgnCorpPartcpCostShrInd', has a \"Yes\", then Schedule G-1 (Form 5471) must be attached to the return.",
  ),
];
