/**
 * MeF Business Rules: F8865
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 40 rules (15 implemented, 25 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, alwaysPass, all, any, eqStr, formPresent, gt, hasNonZero, hasValue, ifThen, } from "../../../../core/validation/mod.ts";

export const F8865_RULES: readonly RuleDef[] = [
  rule(
    "F8865-150-01",
    "reject",
    "missing_document",
    ifThen(hasNonZero("QlfyRehbltExpendRntlREActyAmt"), formPresent("form3468")),
    "If Form 8865, Schedule K, Line 15c 'QlfyRehbltExpendRntlREActyAmt' has a non-zero value, then Form 3468 must be attached to Line 15c.",
  ),
  rule(
    "F8865-188-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NetSection1231GainLossAmt"), formPresent("form4797")),
    "If Form 8865, Schedule K, Line 10 'NetSection1231GainLossAmt' has a non-zero value, then Form 4797 must be attached.",
  ),
  rule(
    "F8865-193-01",
    "reject",
    "missing_data",
    alwaysPass,
    "If Form 8865, Line A2 'CategoryOfFiler2Ind' checkbox is checked, then at least one Schedule K-1 (Form 8865), must be attached to the return.",
  ),
  rule(
    "F8865-194-02",
    "reject",
    "missing_data",
    ifThen(hasValue("OwnsConstructiveInterestInd"), all(any(hasValue("ConstructiveOwnerName"), hasValue("ConstructiveOwnerPersonNm")), any(hasValue("ConstructiveOwnerUSAddress"), hasValue("ConstructiveOwnerFrgnAddress")), any(hasValue("ConstructiveOwnerSSN"), hasValue("ConstructiveOwnerEIN"), hasValue("MissingEINReasonCd")))),
    "If Form 8865, Schedule A, checkbox b 'OwnsConstructiveInterestInd' is checked, then data in the following must be provided: ['ConstructiveOwnerName' or 'ConstructiveOwnerPersonNm'], ['ConstructiveOwnerUSAddress' or 'ConstructiveOwnerFrgnAddress'], and ['ConstructiveOwnerSSN' or 'ConstructiveOwnerEIN' or 'MissingEINReasonCd'].",
  ),
  rule(
    "F8865-195-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NetOfSalesAmt"), any(hasNonZero("GrossReceiptsOrSalesAmt"), hasNonZero("ReturnsAndAllowancesAmt"))),
    "If Form 8865, Schedule B, Line 1c 'NetOfSalesAmt' has a non-zero value, then either Schedule B, Line 1a 'GrossReceiptsOrSalesAmt' or Schedule B, Line 1b 'ReturnsAndAllowancesAmt' must have a non-zero value.",
  ),
  rule(
    "F8865-196-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("GrossProfitAmt"), any(hasNonZero("NetOfSalesAmt"), hasNonZero("CostOfGoodsSoldAmt"))),
    "If Form 8865, Schedule B, Line 3 'GrossProfitAmt' has a non-zero value, then Schedule B, Line 1c 'NetOfSalesAmt' or Schedule B, Line 2 'CostOfGoodsSoldAmt' must have a non-zero value.",
  ),
  rule(
    "F8865-197-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("TotalIncomeOrLossAmt"), any(hasNonZero("GrossProfitAmt"), hasNonZero("OrdinaryIncomeLossOthPrtshpAmt"), hasNonZero("NetFarmProfitLossAmt"), hasNonZero("Form4797GainOrLossAmt"), hasNonZero("OtherIncomeLossAmt"))),
    "If Form 8865, Schedule B, Line 8 'TotalIncomeOrLossAmt' has a non-zero value , then at least one of the following must have a non-zero value: Schedule B, Line 3 'GrossProfitAmt', Schedule B, Line 4 'OrdinaryIncomeLossOthPrtshpAmt', Schedule B, Line 5 'NetFarmProfitLossAmt', Schedule B, Line 6 'Form4797GainOrLossAmt', or Schedule B, Line 7 'OtherIncomeLossAmt'.",
  ),
  rule(
    "F8865-198-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("NetFarmProfitLossAmt"), formPresent("schedule_f")),
    "If Form 8865, Schedule B, Line 5 'NetFarmProfitLossAmt' has a non-zero value, then Schedule-F (Form 1040) must be attached to line 5.",
  ),
  rule(
    "F8865-199-01",
    "reject",
    "missing_data",
    ifThen(hasNonZero("TotalDeductionAmt"), any(hasNonZero("SalariesAndWagesAmt"), hasNonZero("GuaranteedPaymentsToPrtnrAmt"), hasNonZero("RepairsAndMaintenanceAmt"), hasNonZero("BadDebtExpenseAmt"), hasNonZero("RentAmt"), hasNonZero("TaxesAndLicensesAmt"), hasNonZero("InterestAmt"), hasNonZero("DepreciationAmt"), hasNonZero("LessDepreciationAmt"), hasNonZero("DepletionAmt"), hasNonZero("RetirementPlansAmt"), hasNonZero("EmployeeBenefitProgramAmt"), hasNonZero("OtherDeductionsAmt"))),
    "If Form 8865, Schedule B, Line 21 'TotalDeductionAmt' has a non-zero value, then at least one of the following must have a non-zero value: Schedule B, Line 9 'SalariesAndWagesAmt',or Schedule B, Line 10 'GuaranteedPaymentsToPrtnrAmt', or Schedule B, Line 11'RepairsAndMaintenanceAmt', or Schedule B, Line 12 'BadDebtExpenseAmt', or Schedule B, Line 13 'RentAmt', or Schedule B, Line 14 'TaxesAndLicensesAmt', or Schedule B, Line 15 'InterestAmt', or Schedule B, Line 16a 'DepreciationAmt', or Schedule B, Line 16b 'LessDepreciationAmt', or Schedule B, Line 17 'DepletionAmt', or Schedule B, Line 18 'RetirementPlansAmt', or Schedule B, Line 19 'EmployeeBenefitProgramAmt', or Schedule B, Line 20 'OtherDeductionsAmt'.",
  ),
  rule(
    "F8865-202-03",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If Form 8865, Line H2 'FileForm1065Ind' checkbox is checked and Line G2(a) 'ForeignPartnershipEIN' is present, then the first two Digits of Line G2(a) 'ForeignPartnershipEIN' must equal an established District Office Code.",
  ),
  rule(
    "F8865-203-03",
    "reject",
    "missing_document",
    ifThen(hasNonZero("FrgnDisregardedEntitiesOwnNum"), formPresent("IRS8858")),
    "If Form 8865, Line H8 'FrgnDisregardedEntitiesOwnNum' has a non-zero value, then \"IRS8858\" must be attached to Form 8865.",
  ),
  rule(
    "F8865-204-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule B, Line 4 'OrdinaryIncomeLossOthPrtshpAmt' has a non-zero value, then \"Itemized Ordinary Income Loss Statement\" [ItemizedOrdinaryIncomeLossStatement] must be attached to Schedule B, Line 4.",
  ),
  rule(
    "F8865-205-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule B, Line 7 'OtherIncomeLossAmt' has a non-zero value, then \"Itemized Other Income Loss Schedule\" [ItemizedOtherIncomeLossSchedule] must be attached to Schedule B, Line 7.",
  ),
  rule(
    "F8865-206-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule B, Line 20 'OtherDeductionsAmt' has a non-zero value, then \"Itemized Other Deductions Schedule\" [ItemizedOtherDeductionsSchedule2] must be attached to Schedule B, Line 20.",
  ),
  rule(
    "F8865-207-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule K, Line 3b 'ExpensesFromOtherRentalActyAmt' has a non-zero value, then \"Expenses From Other Rental Activities Schedule\" [ExpensesFromOtherRentalActivitiesSchedule] must be attached to Schedule K, Line 3b.",
  ),
  rule(
    "F8865-208-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule K, Line 11 'OtherIncomeLossAmt' has a non-zero value, then \"Itemized Other Income Loss Schedule\" [ItemizedOtherIncomeLossSchedule] must be attached to Schedule K, Line 11.",
  ),
  rule(
    "F8865-209-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule K, Line 13a 'CharitableContributionsTotAmt' has a non-zero value, then \"Charitable Contribution Schedule\" [CharitableContributionSchedule] must be attached to Schedule K, Line 13a.",
  ),
  rule(
    "F8865-210-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule K, Line 13d 'OtherDeductionsAmt' has a non-zero value, then \"Itemized Other Deductions Schedule\" [ItemizedOtherDeductionsSchedule3] must be attached to Schedule K, Line 13d.",
  ),
  rule(
    "F8865-211-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule K, Line 17f 'OtherAMTItemsAmt' has a non-zero value, then \"Other Adjustments And Tax Preference Items Schedule\" [OtherAdjustmentsAndTaxPreferenceItemsSchedule] must be attached to Schedule K, Line 17f.",
  ),
  rule(
    "F8865-212-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 6(b) 'OtherCurrentAssetsBOYAmt' has a non-zero value, then \"Itemized Other Current Assets Schedule\" [ItemizedOtherCurrentAssetsSchedule] must be attached to Schedule L, Line 6(b).",
  ),
  rule(
    "F8865-213-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 6(d) 'OtherCurrentAssetsEOYAmt' has a non-zero value, then \"Itemized Other Current Assets Schedule\" [ItemizedOtherCurrentAssetsSchedule] must be attached to Schedule L, Line 6(d).",
  ),
  rule(
    "F8865-214-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 8(b) 'OtherInvestmentsBOYAmt' has a non-zero value, then \"Itemized Other Investments Schedule\" [ItemizedOtherInvestmentsSchedule] must be attached to Schedule L, Line 8(b).",
  ),
  rule(
    "F8865-215-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 8(d) 'OtherInvestmentsEOYAmt' has a non-zero value, then \"Itemized Other Investments Schedule\" [ItemizedOtherInvestmentsSchedule] must be attached to Schedule L, Line 8(d).",
  ),
  rule(
    "F8865-216-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 13(b) 'OtherAssetsBOYAmt' has a non-zero value, then\"Itemized Other Assets Schedule\" [ItemizedOtherAssetsSchedule] must be attached to Schedule L, Line 13(b).",
  ),
  rule(
    "F8865-217-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 13(d) 'OtherAssetsEOYAmt' has a non-zero value, then \"Itemized Other Assets Schedule\" [ItemizedOtherAssetsSchedule] must be attached to Schedule L, Line 13(d).",
  ),
  rule(
    "F8865-218-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 17(b) 'OtherCurrentLiabilitiesBOYAmt' has a non-zero value, then \"Itemized Other Current Liabilities Schedule\" [ItemizedOtherCurrentLiabilitiesSchedule] must be attached to Schedule L, Line 17(b).",
  ),
  rule(
    "F8865-219-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 17(d) 'OtherCurrentLiabilitiesEOYAmt' has a non-zero value, then \"Itemized Other Current Liabilities Schedule\" [ItemizedOtherCurrentLiabilitiesSchedule] must be attached to Schedule L, Line 17(d).",
  ),
  rule(
    "F8865-220-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 20(b) 'OtherLiabilitiesBOYAmt' has a non-zero value, then \"Itemized Other Liabilities Schedule\" [ItemizedOtherLiabilitiesSchedule] must be attached to Schedule L, Line 20(b).",
  ),
  rule(
    "F8865-221-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule L, Line 20(d) 'OtherLiabilitiesEOYAmt' has a non-zero value, then \"Itemized Other Liabilities Schedule\" [ItemizedOtherLiabilitiesSchedule] must be attached to Schedule L, Line 20(d).",
  ),
  rule(
    "F8865-222-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule M, Line 2c(a) 'TotalForeignAssetsOtherBOYAmt' has a non-zero value, then \"Itemized Other Categories Statement\" [ItemizedOtherCategoriesStatement] must be attached to Schedule M , Line 2c(a).",
  ),
  rule(
    "F8865-223-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule M, Line 2c(b) 'TotalForeignAssetsOtherEOYAmt' has a non-zero value, then \"Itemized Other Categories Statement\" [ItemizedOtherCategoriesStatement] must be attached to Schedule M, Line 2c(b).",
  ),
  rule(
    "F8865-224-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule M-2, Line 4 'TotalOtherIncreasesAmt' has a non-zero value, then \"Itemized Other Increases Schedule\" [ItemizedOtherIncreasesSchedule2] must be attached to Schedule M-2, Line 4.",
  ),
  rule(
    "F8865-225-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8865, Schedule M-2, Line 7 'TotalOtherDecreasesAmt' has a non-zero value, then \"Itemized Other Decrease Schedule\" [ItemizedOtherDecreasesSchedule2] must be attached to Schedule M-2, Line 7.",
  ),
  rule(
    "F8865-226-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("SalariesAndWagesAmt"), gt("SalariesAndWagesAmt", 0)),
    "If Form 8865, Schedule B, Line 9 'SalariesAndWagesAmt' has a non-zero value, then the value must be greater than zero.",
  ),
  rule(
    "F8865-227-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("GuaranteedPaymentsToPrtnrAmt"), gt("GuaranteedPaymentsToPrtnrAmt", 0)),
    "If Form 8865, Schedule B, Line 10 'GuaranteedPaymentsToPrtnrAmt' has a non-zero value, then the value must be greater than zero.",
  ),
  rule(
    "F8865-228-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("RentAmt"), gt("RentAmt", 0)),
    "If Form 8865, Schedule B, Line 13 'RentAmt' has a non-zero value, then the value must be greater than zero.",
  ),
  rule(
    "F8865-229-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("TaxesAndLicensesAmt"), gt("TaxesAndLicensesAmt", 0)),
    "If Form 8865, Schedule B, Line 14 'TaxesAndLicensesAmt' has a non-zero value, then the value must be greater than zero.",
  ),
  rule(
    "F8865-230-01",
    "reject",
    "incorrect_data",
    ifThen(hasNonZero("InterestAmt"), gt("InterestAmt", 0)),
    "If Form 8865, Schedule B, Line 15 'InterestAmt' has a non-zero value, then the value must be greater than zero.",
  ),
  rule(
    "F8865-232-01",
    "reject",
    "missing_data",
    any(hasValue("ForeignPartnershipEIN"), hasValue("ForeignEntityReferenceIdNum")),
    "Form 8865 'ForeignPartnershipEIN' or 'ForeignEntityReferenceIdNum' must have a value.",
  ),
  rule(
    "F8865-233",
    "reject",
    "missing_document",
    ifThen(hasValue("CorrectedInd"), all(hasValue("FormOrSchChgExplnStmt"), eqStr("ScheduleOrFormNum", "8865"))),
    "If Form 8865 'CorrectedInd' is check, then 'FormOrSchChgExplnStmt' must be present and 'ScheduleOrFormNum' must have the value of \"8865\".",
  ),
];
