/**
 * MeF Business Rules: R0000
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 62 rules (10 implemented, 52 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, alwaysPass, alwaysFail, hasValue, hasNonZero, noValue, validSSN, eqStr, eqField, formPresent, formAbsent, ifThen, ifThenUnless, any, all, not, gt, notGtNum, charAfterIsAlpha, charCountAtMost, contains, dateMonthDayEq, dateYearEq, validRTN, } from "../../../../core/validation/mod.ts";

export const R0000_RULES: readonly RuleDef[] = [
  rule(
    "R0000-003",
    "reject_and_stop",
    "missing_data",
    hasValue("returnVersion"),
    "The return version (attribute 'returnVersion' of the Return element) must be specified for each return in the return header.",
  ),
  rule(
    "R0000-004-01",
    "reject_and_stop",
    "data_mismatch",
    alwaysPass,
    "'ReturnTypeCd' (specified in the Return Header) and the return version (specified by the 'returnVersion' attribute of the 'Return' element) of the return must match the return type and the version supported by the Modernized e-File system.",
  ),
  rule(
    "R0000-007-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "For US Addresses, the first five digits of 'ZipCd' of the Filer's address in the Return Header must be within the valid ranges of zip codes for the corresponding 'StateAbbreviationCd'. See Publication 4164.",
  ),
  rule(
    "R0000-019",
    "reject",
    "data_mismatch",
    alwaysPass,
    "The number of return documents (forms, schedules, and supporting documents) included in the return must be equal to the value of the 'documentCnt' attribute of the ReturnData.",
  ),
  rule(
    "R0000-030-01",
    "reject",
    "data_mismatch",
    ifThen(hasValue("PractitionerPINGrp"), eqField("PractitionerPINGrp_EFIN", "OriginatorGrp_EFIN")),
    "If 'PractitionerPINGrp' in the Return Header has a value, then 'EFIN' in 'PractitionerPINGrp' must be the same as 'EFIN' in 'OriginatorGrp'.",
  ),
  rule(
    "R0000-046-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "For US Addresses, the fourth and fifth digit of the 'ZipCd' of the Filer's address in the Return Header cannot both be zeros (\"00\"), except when the 'ZipCd' is 00800, 20500, 34000, 00600, 96100, 96900.",
  ),
  rule(
    "R0000-051-01",
    "reject_and_stop",
    "data_mismatch",
    eqField("FederalSubmissionTypeCd", "ReturnTypeCd"),
    "'FederalSubmissionTypeCd' in the IRS Submission Manifest must match 'ReturnTypeCd' indicated in the Return Header.",
  ),
  rule(
    "R0000-052-01",
    "reject_and_stop",
    "data_mismatch",
    eqField("ManifestTaxYr", "TaxYr"),
    "'TaxYr' specified in the IRS Submission Manifest must match 'TaxYr' in the Return Header.",
  ),
  rule(
    "R0000-054-01",
    "reject_and_stop",
    "data_mismatch",
    eqField("ManifestEFIN", "OriginatorGrp_EFIN"),
    "The 'EFIN' in the IRS Submission Manifest must match 'EFIN' in the 'OriginatorGrp' in the Return Header.",
  ),
  rule(
    "R0000-056-01",
    "reject",
    "missing_document",
    alwaysPass,
    "If Form 8838 is present in the return, then a binary attachment document with Description \"8838 Signature Document\" must be present.",
  ),
  rule(
    "R0000-057-01",
    "reject",
    "missing_data",
    alwaysPass,
    "Every attached file (i.e. binary attachment) must be referenced by the XML document that represents it.",
  ),
  rule(
    "R0000-058-01",
    "reject",
    "missing_data",
    alwaysPass,
    "An XML document that represents a binary attachment must have a valid reference to an attached file.",
  ),
  rule(
    "R0000-060",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "First six digits in the Submission ID must match the EFIN in the Submission Manifest.",
  ),
  rule(
    "R0000-067",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "The attached files (i.e. binary attachments) in a submission zip archive must have distinct names.",
  ),
  rule(
    "R0000-075-02",
    "reject",
    "incorrect_data",
    validRTN("RoutingTransitNum"),
    "'RoutingTransitNum' (RTN) must conform to the banking industry RTN algorithm.",
  ),
  rule(
    "R0000-080-01",
    "reject_and_stop",
    "data_mismatch",
    eqField("ManifestTaxPeriodBeginDt", "TaxPeriodBeginDt"),
    "'TaxPeriodBeginDt' present in the IRS Submission Manifest must match 'TaxPeriodBeginDt' provided in the Return Header.",
  ),
  rule(
    "R0000-081-01",
    "reject_and_stop",
    "data_mismatch",
    eqField("ManifestTaxPeriodEndDt", "TaxPeriodEndDt"),
    "'TaxPeriodEndDt' present in the IRS Submission Manifest must match 'TaxPeriodEndDt' provided in the Return Header.",
  ),
  rule(
    "R0000-082",
    "reject_and_stop",
    "missing_data",
    all(hasValue("TaxPeriodBeginDt"), hasValue("TaxPeriodEndDt")),
    "'TaxPeriodBeginDt' and 'TaxPeriodEndDt' must be provided in the IRS Submission Manifest.",
  ),
  rule(
    "R0000-087-02",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PreparerFirmEIN"), all(not(eqStr("PreparerFirmEIN", "000000000")), not(eqStr("PreparerFirmEIN", "999999999")))),
    "'PreparerFirmEIN' in the Return Header must not equal all zeros or all nines.",
  ),
  rule(
    "R0000-088-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PTIN"), all(not(eqStr("PTIN", "P00000000")), not(eqStr("PTIN", "P99999999")))),
    "The eight numeric digits of the PTIN (of the Paid Preparer) following the letter P, must not equal all zeros or all nines in the Return Header.",
  ),
  rule(
    "R0000-090",
    "alert",
    "database",
    alwaysPass,
    "'ImperfectReturnInd' is checked in the Return Header, but the return does not meet the necessary conditions.",
  ),
  rule(
    "R0000-092-02",
    "reject",
    "incorrect_data",
    validSSN("PrimarySSN"),
    "'PrimarySSN' in the Return Header must be within the valid range of SSN/ITIN and must not be an ATIN.",
  ),
  rule(
    "R0000-093-02",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SpouseSSN"), validSSN("SpouseSSN")),
    "If Spouse SSN in the return has a value, then it must be within the valid range of SSN/ITIN and must not be an ATIN.",
  ),
  rule(
    "R0000-095-02",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PrimarySignaturePIN"), not(eqStr("PrimarySignaturePIN", "00000"))),
    "'PrimarySignaturePIN' in the Return Header must not equal all zeros.",
  ),
  rule(
    "R0000-096-02",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SpouseSignaturePIN"), not(eqStr("SpouseSignaturePIN", "00000"))),
    "'SpouseSignaturePIN' in the Return Header must not equal all zeros.",
  ),
  rule(
    "R0000-113-01",
    "reject",
    "incorrect_data",
    ifThen(hasValue("STIN"), all(not(eqStr("STIN", "S00000000")), not(eqStr("STIN", "S99999999")))),
    "The eight numeric digits of the STIN (of the Paid Preparer) following the letter S, must not equal all zeros or all nines in the Return Header.",
  ),
  rule(
    "R0000-114",
    "reject",
    "incorrect_data",
    ifThen(hasValue("TaxPeriodBeginDt"), dateMonthDayEq("TaxPeriodBeginDt", 1, 1)),
    "The Submission Manifest's 'TaxPeriodBeginDt' value for month and day should be January 1.",
  ),
  rule(
    "R0000-115",
    "reject",
    "incorrect_data",
    ifThen(hasValue("TaxPeriodEndDt"), dateMonthDayEq("TaxPeriodEndDt", 12, 31)),
    "The Submission Manifest's 'TaxPeriodEndDt' value for month and day should be December 31.",
  ),
  rule(
    "R0000-116-02",
    "reject",
    "incorrect_data",
    ifThen(any(eqStr("CityNm", "APO"), eqStr("CityNm", "DPO"), eqStr("CityNm", "FPO")), any(eqStr("StateAbbreviationCd", "AA"), eqStr("StateAbbreviationCd", "AE"), eqStr("StateAbbreviationCd", "AP"))),
    "If the Filer has a US address in the Return Header and if the value of 'CityNm' is \"APO\" or \"DPO\" or \"FPO\", then 'StateAbbreviationCd' must have the value \"AA\", \"AE\" or \"AP\".",
  ),
  rule(
    "R0000-117-01",
    "reject",
    "incorrect_data",
    ifThen(any(eqStr("StateAbbreviationCd", "AA"), eqStr("StateAbbreviationCd", "AE"), eqStr("StateAbbreviationCd", "AP")), any(eqStr("CityNm", "APO"), eqStr("CityNm", "DPO"), eqStr("CityNm", "FPO"))),
    "If the Filer has a US address in the Return Header and 'StateAbbreviationCd' has the value \"AA\", \"AE\" or \"AP\" then the 'CityNm' must be \"APO\" OR \"DPO\" OR \"FPO\".",
  ),
  rule(
    "R0000-118-01",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "If first two digits of the EFIN in the IRS Submission Manifest are 10, 21, 32, 44 or 53, then 'OriginatorTypeCd' in the Return Header must have the value \"OnlineFiler\".",
  ),
  rule(
    "R0000-119-01",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "If 'OriginatorTypeCd' in the Return Header has the value \"OnlineFiler\", then the first two digits of the EFIN in the IRS Submission Manifest must be 10 or 21 or 32 or 44 or 53.",
  ),
  rule(
    "R0000-120",
    "reject_and_stop",
    "unsupported",
    alwaysPass,
    "The IRS Submission type that was filed is not being accepted by Modernized e-File (MeF) at this time.  Please check the MeF web page under irs.gov for more information.  The submission type filed was <type>.",
  ),
  rule(
    "R0000-121",
    "reject_and_stop",
    "unsupported",
    alwaysPass,
    "The ETIN associated with the Individual submission is not a participating transmitter.  Please check the Modernized e-File (MeF) web page under irs.gov for more information on participation rules.",
  ),
  rule(
    "R0000-123-01",
    "reject",
    "missing_data",
    ifThen(contains("NameLine1Txt", "&"), hasValue("SpouseSSN")),
    "If 'NameLine1Txt' in the Return Header contains an ampersand, then 'SpouseSSN' in the Return Header must have a value.",
  ),
  rule(
    "R0000-125-01",
    "reject",
    "incorrect_data",
    contains("NameLine1Txt", "<"),
    "'NameLine1Txt' in the Return Header must contain a less-than sign (<).",
  ),
  rule(
    "R0000-126-01",
    "reject",
    "incorrect_data",
    charCountAtMost("NameLine1Txt", "<", 2),
    "There can be no more than two less-than signs (<) in 'NameLine1Txt' in the Return Header.",
  ),
  rule(
    "R0000-127-01",
    "reject",
    "incorrect_data",
    charAfterIsAlpha("NameLine1Txt", "<"),
    "The character following the first less-than sign in 'NameLine1Txt' in the Return Header must be an alphabetic character.",
  ),
  rule(
    "R0000-129-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "The 4th and 5th digits of the 'PrimarySSN' in the Return Header must be equal to \"00\" for testing.",
  ),
  rule(
    "R0000-130-01",
    "reject",
    "incorrect_data",
    alwaysPass,
    "The 4th and 5th digits of Spouse SSN in the return must be equal to \"00\" for testing.",
  ),
  rule(
    "R0000-142-01",
    "alert",
    "incorrect_data",
    alwaysPass,
    "If you are a paid tax return preparer, you must use a Preparer Tax Identification Number (PTIN) issued by the Internal Revenue Service (IRS) to identify yourself in the paid preparer section of the tax return. In future years, tax returns may be rejected if an SSN, or any number that is not a valid PTIN, is included in this field.",
  ),
  rule(
    "R0000-143",
    "reject_and_stop",
    "missing_data",
    hasValue("TaxYr"),
    "'TaxYr' in the IRS Submission Manifest must have a value.",
  ),
  rule(
    "R0000-180",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "'TaxYr' specified in the Submission Manifest must equal the year of the schema version ('YYYY' digits of the attribute 'returnVersion' of the Return) that is being used to file the return.",
  ),
  rule(
    "R0000-192",
    "reject",
    "incorrect_data",
    ifThen(hasValue("PhoneNum"), not(eqStr("PhoneNum", "0000000000"))),
    "Phone Number provided in the return must not be all zeros.",
  ),
  rule(
    "R0000-193",
    "reject",
    "incorrect_data",
    alwaysPass,
    "Bank Account Number provided in the return must not be all zeros.",
  ),
  rule(
    "R0000-194",
    "reject_and_stop",
    "duplicate",
    alwaysPass,
    "Submission must not be a duplicate of a previously accepted submission.",
  ),
  rule(
    "R0000-198",
    "reject_and_stop",
    "incorrect_data",
    alwaysPass,
    "This return is ineligible to be filed electronically.",
  ),
  rule(
    "R0000-204",
    "reject",
    "missing_document",
    ifThen(hasNonZero("QualifiedBusinessIncomeDedAmt"), any(formPresent("form8995"), formPresent("form8995a"))),
    "If 'QualifiedBusinessIncomeDedAmt' in the return (1040, 1040NR, 1041) has a non-zero value, then one and only one Form 8995 or Form 8995A must be present in the return.",
  ),
  rule(
    "R0000-205",
    "reject",
    "math_error",
    alwaysPass,
    "If 'QualifiedBusinessIncomeDedAmt' in the return (1040, 1040NR, 1041) has a non-zero value, then it cannot be more than the sum of Form 8995-A, 'DPADSect199AGAllocAgricHortAmt' and the lesser of the QBI Limitation or TXI Limitation.",
  ),
  rule(
    "R0000-225",
    "reject_and_stop",
    "unsupported",
    alwaysPass,
    "This submission contains a form or schedule that is not currently supported for electronic filing.",
  ),
  rule(
    "R0000-228",
    "reject_and_stop",
    "incorrect_data",
    dateYearEq("TaxPeriodBeginDt", "TaxYr"),
    "'TaxYr' must equal the year of the 'TaxPeriodBeginDt' (\"YYYY\" digits) in the Submission Manifest.",
  ),
  rule(
    "R0000-229",
    "reject_and_stop",
    "incorrect_data",
    dateYearEq("TaxPeriodEndDt", "TaxYr"),
    "'TaxYr' must equal the year of the 'TaxPeriodEndDt' (\"YYYY\" digits) in the Submission Manifest.",
  ),
  rule(
    "R0000-235",
    "reject",
    "missing_document",
    ifThen(formPresent("schedule_a_form8936"), formPresent("form8936")),
    "If Schedule A (Form 8936) is present in the return, then Form 8936 must also be present.",
  ),
  rule(
    "R0000-236",
    "reject_and_stop",
    "unsupported",
    alwaysPass,
    "This submission contains a form or schedule which MeF is not accepting as a binary attachment. Please verify whether it is valid for your submission to include the form or schedule. If valid, complete the form or schedule in XML format and resubmit.",
  ),
  rule(
    "R0000-500-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "'PrimarySSN' and 'PrimaryNameControlTxt' in the Return Header must match the e-File database.",
  ),
  rule(
    "R0000-503-02",
    "reject_and_stop",
    "database",
    alwaysPass,
    "Spouse SSN and Spouse Name Control in the return must match the e-File database.",
  ),
  rule(
    "R0000-504-02",
    "reject",
    "database",
    alwaysPass,
    "Each 'DependentSSN' and the corresponding 'DependentNameControlTxt' that has a value in 'DependentDetail' in the return must match the SSN and Name Control in the e-File database.",
  ),
  rule(
    "R0000-533-02",
    "reject",
    "incorrect_data",
    alwaysPass,
    "If a Dependent's Date of Death has a value in the e-File database, then it must not be prior to 'TaxYr' in the Return Header.",
  ),
  rule(
    "R0000-571-02",
    "reject",
    "database",
    alwaysPass,
    "For each DependentSSN in the tax return, the Year of Birth in the e-File database must not be greater than 'TaxYr' in the Return Header.",
  ),
  rule(
    "R0000-904-03",
    "reject_and_stop",
    "database",
    alwaysPass,
    "Software ID in the Return Header must have passed testing for the form family and 'TaxYr'.",
  ),
  rule(
    "R0000-905-01",
    "reject_and_stop",
    "database",
    alwaysPass,
    "Electronic Filing Identification Number (EFIN) in the Return Header must be listed in the e-File database and in accepted status.",
  ),
  rule(
    "R0000-906-02",
    "reject",
    "database",
    alwaysPass,
    "Routing Transit Number (RTN) included in the return must be present in the e-File database.",
  ),
];
