/**
 * MeF Business Rules: SK2
 * Auto-generated from 1040_Business_Rules_2025v3.0.csv
 * 32 rules (32 implemented, 0 stubs)
 */

import type { RuleDef } from "../../../../core/validation/types.ts";
import { rule, all, any, eqStr, formCountAtMost, hasValue, ifThen, isZero, } from "../../../../core/validation/mod.ts";

export const SK2_RULES: readonly RuleDef[] = [
  rule(
    "SK2-F8865-005-01",
    "reject",
    "missing_data",
    ifThen(eqStr("PartIAttachedInd", "Yes"), any(hasValue("GainOnPersonalPropertySaleInd"), hasValue("ForeignOilAndGasTaxesInd"), hasValue("SplitterArrangementsInd"), hasValue("ForeignTaxTranslationInd"), hasValue("HighTaxedIncomeInd"), hasValue("Sect267ADisallowedDedInd"), hasValue("Form5471AttachmentInd"), hasValue("OtherFormsAttachmentInd"), hasValue("PartnerLoanTransactionsInd"), hasValue("DualConsolidatedLossInd"), hasValue("OtherInternationalItemsInd"))),
    "If Schedule K-2 (Form 8865), 'PartIAttachedInd' has a choice of \"Yes\" indicated, then at least one of the following must be checked: 'GainOnPersonalPropertySaleInd' or 'ForeignOilAndGasTaxesInd' or 'SplitterArrangementsInd' or 'ForeignTaxTranslationInd' or 'HighTaxedIncomeInd' or 'Sect267ADisallowedDedInd' or 'Form5471AttachmentInd' or 'OtherFormsAttachmentInd' or 'PartnerLoanTransactionsInd' or 'DualConsolidatedLossInd' or 'OtherInternationalItemsInd'.",
  ),
  rule(
    "SK2-F8865-006-01",
    "reject",
    "incorrect_data",
    ifThen(any(hasValue("GainOnPersonalPropertySaleInd"), hasValue("ForeignOilAndGasTaxesInd"), hasValue("SplitterArrangementsInd"), hasValue("ForeignTaxTranslationInd"), hasValue("HighTaxedIncomeInd"), hasValue("Sect267ADisallowedDedInd"), hasValue("Form5471AttachmentInd"), hasValue("OtherFormsAttachmentInd"), hasValue("PartnerLoanTransactionsInd"), hasValue("DualConsolidatedLossInd"), hasValue("OtherInternationalItemsInd")), eqStr("PartIAttachedInd", "Yes")),
    "If any of the following are checked on Schedule K-2 (Form 8865), then 'PartIAttachedInd' must have a choice of \"Yes\" indicated: 'GainOnPersonalPropertySaleInd' or 'ForeignOilAndGasTaxesInd' or 'SplitterArrangementsInd' or 'ForeignTaxTranslationInd' or 'HighTaxedIncomeInd' or 'Sect267ADisallowedDedInd' or 'Form5471AttachmentInd' or 'OtherFormsAttachmentInd' or 'PartnerLoanTransactionsInd' or 'DualConsolidatedLossInd' or 'OtherInternationalItemsInd'.",
  ),
  rule(
    "SK2-F8865-007",
    "reject",
    "missing_data",
    ifThen(eqStr("PartIIAttachedInd", "Yes"), any(hasValue("Frm8865GrossIncomeGrp"), hasValue("SchK2K3FrgnTaxCreditDedGrp"))),
    "If Schedule K-2 (Form 8865), 'PartIIAttachedInd' has a choice of \"Yes\" indicated, then 'Frm8865GrossIncomeGrp' or 'SchK2K3FrgnTaxCreditDedGrp' must have a value.",
  ),
  rule(
    "SK2-F8865-008",
    "reject",
    "incorrect_data",
    ifThen(any(hasValue("Frm8865GrossIncomeGrp"), hasValue("SchK2K3FrgnTaxCreditDedGrp")), eqStr("PartIIAttachedInd", "Yes")),
    "If Schedule K-2 (Form 8865), 'Frm8865GrossIncomeGrp' or 'SchK2K3FrgnTaxCreditDedGrp' has a value, then 'PartIIAttachedInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "SK2-F8865-009",
    "reject",
    "missing_data",
    ifThen(eqStr("PartIIIAttachedInd", "Yes"), any(hasValue("SchK2K3REExpnssApprtnFctrGrp"), hasValue("SchK2K3IntExpnsApprtnFctrGrp"), hasValue("SchK2K3FDIIDedApprtnFctrsGrp"), hasValue("SchK2K3ForeignTaxesGrp"), hasValue("SchK2K3OtherTaxInformationGrp"))),
    "If Schedule K-2 (Form 8865), 'PartIIIAttachedInd' has a choice of \"Yes\" indicated, then 'SchK2K3REExpnssApprtnFctrGrp' or 'SchK2K3IntExpnsApprtnFctrGrp' or 'SchK2K3FDIIDedApprtnFctrsGrp' or 'SchK2K3ForeignTaxesGrp' or 'SchK2K3OtherTaxInformationGrp' must have a value.",
  ),
  rule(
    "SK2-F8865-010",
    "reject",
    "incorrect_data",
    ifThen(any(hasValue("SchK2K3REExpnssApprtnFctrGrp"), hasValue("SchK2K3IntExpnsApprtnFctrGrp"), hasValue("SchK2K3FDIIDedApprtnFctrsGrp"), hasValue("SchK2K3ForeignTaxesGrp"), hasValue("SchK2K3OtherTaxInformationGrp")), eqStr("PartIIIAttachedInd", "Yes")),
    "If any of the following on Schedule K-2 (Form 8865) have values, then 'PartIIIAttachedInd' must have a choice of \"Yes\" indicated: 'SchK2K3REExpnssApprtnFctrGrp' or 'SchK2K3IntExpnsApprtnFctrGrp' or 'SchK2K3FDIIDedApprtnFctrsGrp' or 'SchK2K3ForeignTaxesGrp' or 'SchK2K3OtherTaxInformationGrp'.",
  ),
  rule(
    "SK2-F8865-011",
    "reject",
    "missing_data",
    ifThen(eqStr("PartIVAttachedInd", "Yes"), hasValue("SchK2K3PrtnrSect250DedFDIIGrp")),
    "If Schedule K-2 (Form 8865) 'PartIVAttachedInd' has a choice of \"Yes\" indicated, then 'SchK2K3PrtnrSect250DedFDIIGrp' must have a value.",
  ),
  rule(
    "SK2-F8865-012",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SchK2K3PrtnrSect250DedFDIIGrp"), eqStr("PartIVAttachedInd", "Yes")),
    "If Schedule K-2 (Form 8865), 'SchK2K3PrtnrSect250DedFDIIGrp' has a value, then 'PartIVAttachedInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "SK2-F8865-013",
    "reject",
    "missing_data",
    ifThen(eqStr("PartVAttachedInd", "Yes"), hasValue("SchK2K3FrgnCorpDistriPrtshpGrp")),
    "If Schedule K-2 (Form 8865), 'PartVAttachedInd' has a choice of \"Yes\" indicated, then 'SchK2K3FrgnCorpDistriPrtshpGrp' must have a value.",
  ),
  rule(
    "SK2-F8865-014",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SchK2K3FrgnCorpDistriPrtshpGrp"), eqStr("PartVAttachedInd", "Yes")),
    "If Schedule K-2 (Form 8865), 'SchK2K3FrgnCorpDistriPrtshpGrp' has a value, then 'PartVAttachedInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "SK2-F8865-015",
    "reject",
    "missing_data",
    ifThen(eqStr("PartVIAttachedInd", "Yes"), hasValue("SchK2K3PrtnrSect951a1InclsnGrp")),
    "If Schedule K-2 (Form 8865), 'PartVIAttachedInd' has a choice of \"Yes\" indicated, then 'SchK2K3PrtnrSect951a1InclsnGrp' must have a value.",
  ),
  rule(
    "SK2-F8865-016",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SchK2K3PrtnrSect951a1InclsnGrp"), eqStr("PartVIAttachedInd", "Yes")),
    "If Schedule K-2 (Form 8865), 'SchK2K3PrtnrSect951a1InclsnGrp' has a value, then 'PartVIAttachedInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "SK2-F8865-017",
    "reject",
    "missing_data",
    ifThen(eqStr("PartVIIAttachedInd", "Yes"), hasValue("SchK2K3InfoToComplete8621Grp")),
    "If Schedule K-2 (Form 8865), 'PartVIIAttachedInd' has a choice of \"Yes\" indicated, then 'SchK2K3InfoToComplete8621Grp' must have a value.",
  ),
  rule(
    "SK2-F8865-018",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SchK2K3InfoToComplete8621Grp"), eqStr("PartVIIAttachedInd", "Yes")),
    "If Schedule K-2 (Form 8865), 'SchK2K3InfoToComplete8621Grp' has a value, then 'PartVIIAttachedInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "SK2-F8865-021",
    "reject",
    "missing_data",
    ifThen(eqStr("PartVIIIAttachedInd", "Yes"), hasValue("SchK2PartnerInfoBEATGrp")),
    "If Schedule K-2 (Form 8865), 'PartVIIIAttachedInd' has a choice of \"Yes\" indicated, then 'SchK2PartnerInfoBEATGrp' must have a value.",
  ),
  rule(
    "SK2-F8865-022",
    "reject",
    "incorrect_data",
    ifThen(hasValue("SchK2PartnerInfoBEATGrp"), eqStr("PartVIIIAttachedInd", "Yes")),
    "If Schedule K-2 (Form 8865), 'SchK2PartnerInfoBEATGrp' has a value, then 'PartVIIIAttachedInd' must have a choice of \"Yes\" indicated.",
  ),
  rule(
    "SK2-F8865-023",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'SalesGrossIncomeGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-024",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'GrossIncmPerfOfSrvcGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-025",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'GroRntlRealEstateIncmGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-026",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'OthGrossRentalIncomeGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-027",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'SchK2K3InterestIncomeGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-028",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'SchK2K3OrdinaryDividendsGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-029",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'QualifiedDividendsGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-030",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'RoyaltiesLicenseFeesGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-031",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'NetShortTermCapGainGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-032",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'NetLongTermCapGainGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-033",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'CollectiblesGainGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-034",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'SchK2K3UnrcptrSect1250GainGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-035",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'SchK2K3NetSection1231GainGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-036",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'SchK2K3OtherIncomeGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-037",
    "reject",
    "incorrect_data",
    ifThen(eqStr("OtherCategoryDescriptionCd", "XX"), all(isZero("USSourceIncomeAmt"), isZero("ForeignBranchIncomeAmt"), isZero("PassiveCategoryIncomeAmt"), isZero("GeneralCategoryIncomeAmt"), isZero("OtherCategoryIncomeAmt"))),
    "If Schedule K-2 (Form 8865), 'OtherCategoryDescriptionCd' in 'TotGrossIncomeByCountryGrp', has the value \"XX\", then the corresponding 'USSourceIncomeAmt' and 'ForeignBranchIncomeAmt' and 'PassiveCategoryIncomeAmt' and 'GeneralCategoryIncomeAmt' and 'OtherCategoryIncomeAmt' must be zero, if amounts are entered.",
  ),
  rule(
    "SK2-F8865-099",
    "reject",
    "incorrect_data",
    formCountAtMost("scheduleK2Form8865", 1),
    "If Schedule K-2 (Form 8865) is present in the return, then it must be referenced from one and only one Form 8865.",
  ),
];
