export const form8854InitialCash = {
  expatriation_date: "2025-06-15",
  expatriate_type: "CITIZEN",
  tax_status_2025: "FULL_YEAR_US_CITIZEN_OR_RESIDENT",
  part_i: {
    mailing_address: {
      kind: "US",
      line1: "1 Main St",
      city: "Wilmington",
      state: "DE",
      zip: "19801",
    },
    telephone: { kind: "US", number: "3025550123" },
    notification: {
      kind: "CITIZEN_STATE_DEPARTMENT",
      date: "2025-06-15",
    },
    citizenships: [{ country_code: "US", acquired_date: "1980-01-01" }],
    us_citizenship_acquisition: "BIRTH",
  },
  prior_year_us_income_tax_less_foreign_tax_credit: {
    year_2024: 80,
    year_2023: 0,
    year_2022: 0,
    year_2021: 0,
    year_2020: 0,
  },
  prior_year_filed_return_sources: [2020, 2021, 2022, 2023, 2024].map(
    (year) => ({
      tax_year: year,
      filed_form1040_document_id: `filed-${year}-form1040`,
      filed_form1040_sha256: String(year).repeat(16),
      form1040_line24_total_tax: year === 2024 ? 100 : 0,
      schedule3_line1_foreign_tax_credit: year === 2024 ? 20 : 0,
      irs_acceptance_reference: `irs-accepted-${year}`,
    }),
  ),
  balance_sheet: {
    asset_categories_confirmed_complete: true,
    liabilities_confirmed_complete: true,
    cash_and_bank_deposits: {
      fair_market_value: 100_000,
      us_adjusted_basis: 100_000,
    },
    foreign_cfc_securities_within_line5: [],
    partnership_interests: [],
    owned_trust_assets: [],
    nongrantor_trust_interests: [],
    other_assets: [],
    installment_obligations_liability: 0,
    mortgage_liability: 0,
    other_liabilities: [],
  },
  certified_tax_compliance: true,
  exception_facts: { dual_citizen: null, minor: null },
  significant_asset_liability_changes_prior_5_years: false,
  section_c: null,
  section_d: { elect_deferral: false },
};
