import { FilingStatus } from "../mef/header.ts";
import { type F5471Item, FilingCategory } from "../nodes/inputs/f5471/index.ts";

export const form8992Cfc: F5471Item = {
  foreign_corp_name: "Example Foreign Corp",
  foreign_corp_reference_id: "FC001",
  country_of_incorporation: "EI",
  functional_currency: "EUR",
  filing_category: FilingCategory.Category5a,
  shareholder_tin: "111223333",
  ownership_percent: 100,
  section_962_election: false,
  reviewed_form5471_source_reference: "Reviewed Form 5471",
  schedule_i: {
    line1a: 2_000,
    line1b: 0,
    line1c: 0,
    line1d: 0,
    line1e: 8_000,
    line1f: 0,
    line1g: 0,
    line1h: 0,
    line2_us_property: 1_000,
    line4_factoring: 0,
    line5a_eligible_dividends: 0,
    line5b_extraordinary_disposition: 0,
    line5c_extraordinary_reduction: 0,
    line5d_hybrid_dividends: 0,
    line5e_other_dividends: 0,
    line6_exchange_gain_or_loss: 0,
    income_blocked: false,
    income_unblocked: false,
    extraordinary_disposition_account: false,
    hybrid_deduction_accounts: 0,
    worksheet_a_reference: "Reviewed Worksheet A",
    worksheet_b_reference: "Reviewed Worksheet B",
  },
  schedule_i1: {
    separate_category: "GEN",
    average_exchange_rate: "1.0000",
    gross_income_functional: 65_000,
    effectively_connected_income_functional: 0,
    subpart_f_income_functional: 10_000,
    high_tax_exception_income_functional: 0,
    related_party_dividends_functional: 0,
    foreign_oil_gas_income_functional: 0,
    allocable_deductions_functional: 5_000,
    tested_foreign_taxes_functional: 500,
    tested_foreign_taxes_usd: 500,
    qbai_functional: 100_000,
    interest_expense_functional: 3_000,
    qualified_interest_expense_functional: 0,
    tested_loss_qbai_functional: 0,
    tested_interest_expense_functional: 3_000,
    interest_income_functional: 1_000,
    qualified_interest_income_functional: 0,
    tested_interest_income_functional: 1_000,
    tested_income: 50_000,
    pro_rata_tested_income: 50_000,
    pro_rata_qbai: 100_000,
    pro_rata_tested_interest_income: 1_000,
    pro_rata_tested_interest_expense: 3_000,
    schedule_i1_source_reference: "Reviewed Schedule I-1",
  },
  schedule_h: {
    book_net_income_functional: 50_000,
    adjustments: {
      capital_gain_add: 0,
      capital_gain_subtract: 0,
      depreciation_add: 0,
      depreciation_subtract: 0,
      depletion_add: 0,
      depletion_subtract: 0,
      investment_allowance_add: 0,
      investment_allowance_subtract: 0,
      statutory_reserves_add: 0,
      statutory_reserves_subtract: 0,
      inventory_add: 0,
      inventory_subtract: 0,
      income_taxes_add: 0,
      income_taxes_subtract: 0,
      foreign_currency_add: 0,
      foreign_currency_subtract: 0,
      other_add: 0,
      other_subtract: 0,
    },
    dastm_gain_or_loss: 0,
    passive_category_ep: 0,
    section901j_category_ep: 0,
    current_ep_usd: 50_000,
    average_exchange_rate: "1.0000",
    source_workpaper_reference: "Reviewed Schedule H book-to-E&P workpaper",
  },
  schedule_e: {
    tax_country_code: "EI",
    foreign_tax_year_end: "2025-12-31",
    us_tax_year_end: "2025-12-31",
    taxable_income_local: 50_000,
    local_currency: "EUR",
    tax_local: 500,
    tax_conversion_rate: "1.0000",
    tax_usd: 500,
    tax_functional: 500,
    section986_election: false,
    lower_tier_deemed_paid_tax: 0,
    disallowed_tax: 0,
    prior_year_tax_balance: 0,
    other_e1_adjustments: 0,
    taxes_deemed_paid_on_inclusion: 0,
    ptep_tax: 0,
    source_workpaper_reference: "Reviewed Schedule E/E-1 tax workpaper",
  },
  schedule_g: {
    q1_foreign_partnership: false,
    q2_trust: false,
    q3a_foreign_entity_or_branch: false,
    q3b_different_currency_qbu: false,
    q4a_base_erosion: false,
    q5a_disallowed_267a: false,
    q6a_fdii: false,
    q7_cost_sharing: false,
    q8_triangular_stock: false,
    q9a_intangible_property: false,
    q10_expatriated_subsidiary: false,
    q11_reportable_transaction: false,
    q12_disqualified_901m_tax: false,
    q13_section909_tax: false,
    q14_special_exceptions: false,
    q15_disallowed_interest: false,
    q16_interest_carryforward: false,
    q17a_extraordinary_reduction: false,
    q18a_safe_haven_rate: false,
    q18b_outside_safe_haven_rate: false,
    q19a_covered_debt: false,
    q20a_top_up_tax: false,
    q21a_section304_ep: false,
    source_workpaper_reference: "Reviewed Schedule G questions",
  },
  form5471_identity: {
    cfc_tax_year_begin: "2025-01-01",
    cfc_tax_year_end: "2025-12-31",
    filer_tax_year_begin: "2025-01-01",
    filer_tax_year_end: "2025-12-31",
    foreign_address: {
      line1: "1 River Street",
      city: "Dublin",
      country_code: "EI",
      postal_code: "D02 ABC1",
    },
    incorporation_date: "2020-01-01",
    principal_business_country_code: "EI",
    principal_business_activity_code: "541990",
    principal_business_activity_description: "Professional services",
    books_custodian_business_name: "Example Foreign Corp",
    books_at_cfc_address: true,
    statutory_agent_business_name: "Example Agent Ltd",
    statutory_agent_at_cfc_address: true,
    no_us_branch_or_agent: true,
    no_us_tax_return: true,
    no_joint_filing_for_other_persons: true,
    stock_class_description: "Common",
    direct_shares_begin: 100,
    direct_shares_end: 100,
    total_outstanding_shares_begin: 100,
    total_outstanding_shares_end: 100,
    source_workpaper_reference:
      "Reviewed Form 5471 identity and stock register",
  },
};

export const form8992Filer = {
  primarySSN: "111223333",
  firstName: "Alex",
  lastName: "Taxpayer",
  nameLine1: "Alex Taxpayer",
  nameControl: "TAXP",
  address: {
    line1: "1 Test Way",
    city: "Austin",
    state: "TX",
    zip: "78701",
  },
  filingStatus: FilingStatus.Single,
} as const;

export const form8992Pending = {
  f5471: { f5471s: [form8992Cfc] },
  schedule1: {
    line8n_section951a_inclusion: 11_000,
    line8o_section951aa_inclusion: 42_000,
  },
} as const;
