export function form6251Form4952Fixture() {
  const prior = {
    tax_year: 2024,
    filed_return_reference: "2024 reviewed accepted return",
    completed_form_reference: "2024 filed Form 4952",
    filed_primary_ssn: "123456789",
    reviewed_by: "Tax Reviewer",
    reviewed_on: "2026-09-30",
    filed_2024_form4952: {
      line1: 3_000,
      line2: 0,
      line3: 3_000,
      line6: 1_000,
      line7: 2_000,
      line8: 1_000,
    },
    filed_2024_schedule_a_line9: 1_000,
    prior_interest_entirely_schedule_a_confirmed: true,
    prior_no_form6198_allocation_confirmed: true,
    reviewed_2024_amt_form4952_line7: 4_000,
  };
  return {
    general: {
      filing_status: "single",
      taxpayer_first_name: "Alex",
      taxpayer_last_name: "Taxpayer",
      taxpayer_ssn: "123-45-6789",
      taxpayer_dob: "1980-06-15",
    },
    w2: [{ box1_wages: 200_000, box2_fed_withheld: 35_000 }],
    f1099int: [{
      payer_name: "Taxable bond payer",
      source_document_reference: "2025 taxable bond Form 1099-INT",
      box1: 23_000,
      investment_property_for_form4952: true,
    }],
    schedule_b_part_iii: {
      foreign_accounts_question: false,
      fincen_form114_required: false,
      foreign_trust_question: false,
    },
    form4952: {
      investment_interest_expense: 20_000,
      direct_debt_trace: {
        tax_year: 2025,
        owner_tin: "123456789",
        loan_id: "taxable-bond-purchase-loan",
        lender_statement_reference: "lender-2025-statement",
        loan_agreement_reference: "loan-agreement",
        disbursement_record_reference: "bank-disbursement",
        purchase_record_reference: "bond-purchase-record",
        loan_date: "2025-01-10",
        direct_purchase_date: "2025-01-10",
        borrowed_principal: 100_000,
        direct_taxable_securities_purchase: 100_000,
        asset_id: "taxable-bond-lot",
        no_other_loan_proceeds_use: true,
        no_tax_exempt_or_passive_activity_asset: true,
        investment_use_maintained_through_2025: true,
        lender_2025_interest_total: 20_000,
        interest_payments: [{
          payment_id: "june-payment",
          payment_date: "2025-06-30",
          payment_record_reference: "bank-june",
          interest_amount: 10_000,
        }, {
          payment_id: "december-payment",
          payment_date: "2025-12-31",
          payment_record_reference: "bank-december",
          interest_amount: 10_000,
        }],
      },
      prior_year_carryforward: 2_000,
      prior_year_carryforward_source: prior,
      amt_refigure: {
        prior_year_disallowed_interest: 4_000,
        interest_on_private_activity_bonds: 0,
        other_gross_income_adjustment: 0,
        qualified_dividends_adjustment: 0,
        net_disposition_gain_adjustment: 0,
        net_capital_gain_adjustment: 0,
        investment_expenses_adjustment: 0,
      },
    },
    f3921: [{
      source_document_reference: "2025 issued Form 3921 retained lot",
      corporation_name: "Option Corporation",
      corporation_ein: "12-3456789",
      employee_tin: "123-45-6789",
      box1_date_option_granted: "2022-06-01",
      box2_date_option_exercised: "2025-06-02",
      box3_exercise_price_per_share: 10,
      box4_fmv_per_share: 250,
      box5_shares_transferred: 1_000,
      rights_transferable_and_not_subject_to_substantial_risk_on_exercise: true,
      shares_disposed_during_exercise_year: 0,
      amount_paid_for_option: 0,
    }],
  };
}
