export const form8854AnnualNoEvent = {
  expatriation_date: "2020-06-15",
  expatriate_type: "CITIZEN",
  part_i: {
    mailing_address: {
      kind: "US",
      line1: "1 Main St",
      city: "Wilmington",
      state: "DE",
      zip: "19801",
    },
    telephone: { kind: "US", number: "3025550123" },
    notification: {
      kind: "CITIZEN_STATE_DEPARTMENT",
      date: "2020-06-15",
    },
    citizenships: [{ country_code: "US", acquired_date: "1980-01-01" }],
    us_citizenship_acquisition: "BIRTH",
  },
  tax_status_2025: "FULL_YEAR_US_CITIZEN_OR_RESIDENT",
  prior_form8854_obligations_confirmed_complete: true,
  prior_form8854_obligation_ledger: {
    source_document_id: "DOC-PRIOR",
    source_sha256: "c".repeat(64),
    filed_tax_year: 2024,
    irs_acceptance_reference: "irs-accepted-2024-form8854",
    deferred_properties: [{
      item_id: "stock",
      description: "Stock holding",
      mark_to_market_gain_or_loss_amount: 111_000,
      deferred_tax_amount: 50_000,
    }],
    eligible_deferred_compensation_items: [],
    nongrantor_trust_interests: [],
  },
  original_form8854_mailed_confirmed: true,
  attached_form8854_copy_marked_copy_confirmed: true,
  source_1042s: [],
  deferred_properties: [{
    item_id: "stock",
    description: "Stock holding",
    prior_form8854_document_id: "DOC-PRIOR",
    prior_mark_to_market_gain_or_loss_amount: 111_000,
    prior_deferred_tax_amount: 50_000,
    disposition: { disposed_in_2025: false },
  }],
  eligible_deferred_compensation_items: [],
  nongrantor_trust_interests: [],
};
